/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Jail_ts2022.views;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.Timer;
import Jail_ts2022.conexao.Conectar;

/**
 *
 * @author Mutisse
 */
public final class CaregarOPrograma extends javax.swing.JFrame {
    // variaves de conexao

    Connection conexao = null;
    PreparedStatement stat = null; //pst quer dizer  PreparedStatement
    ResultSet rst = null;

    /**
     * Creates new form Login
     */
    public CaregarOPrograma() {
        initComponents();
        setIconImage();
        HoraData();

        conexao = Conectar.conector();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_imagem = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        JProgressBar = new javax.swing.JProgressBar();
        lbl_boasVindas = new javax.swing.JLabel();
        lbl_horaData = new javax.swing.JLabel();
        lbl_texto = new javax.swing.JLabel();
        lbl_Conexao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(" Login");
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(214, 217, 223));
        jPanel1.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        jPanel1.setLayout(null);

        lbl_imagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbl_imagem);
        lbl_imagem.setBounds(90, 10, 140, 140);

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(250, 180, 40, 10);

        JProgressBar.setBackground(new java.awt.Color(214, 217, 223));
        JProgressBar.setForeground(new java.awt.Color(153, 255, 255));
        jPanel1.add(JProgressBar);
        JProgressBar.setBounds(10, 195, 280, 10);

        lbl_boasVindas.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jPanel1.add(lbl_boasVindas);
        lbl_boasVindas.setBounds(10, 140, 200, 15);

        lbl_horaData.setFont(new java.awt.Font("Segoe UI", 3, 10)); // NOI18N
        jPanel1.add(lbl_horaData);
        lbl_horaData.setBounds(10, 160, 230, 15);

        lbl_texto.setFont(new java.awt.Font("Segoe UI", 3, 10)); // NOI18N
        lbl_texto.setText("Aguarde..");
        jPanel1.add(lbl_texto);
        lbl_texto.setBounds(10, 180, 90, 10);
        jPanel1.add(lbl_Conexao);
        lbl_Conexao.setBounds(10, 10, 40, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(307, 213));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * ************************ Metodos ***************************
     */
    public void HoraData() {
        Date data = new Date();
        sdf = new SimpleDateFormat("dd MMMM yyyy");
        Calendar now = Calendar.getInstance();
        class hora implements ActionListener {

            @Override
            public void actionPerformed(ActionEvent e) {
                Calendar now = Calendar.getInstance();
                lbl_horaData.setText(String.format("Data: " + sdf.format(data) + ",  Horas:  " + "%1$tH : %1$tM : %1$tS", now));

            }

        }

        Timer timer = new Timer(1000, new hora());
        timer.start();
        Calendar c1 = Calendar.getInstance();
        int hora = c1.get(Calendar.HOUR_OF_DAY);

        if (hora <= 12 && hora <= 12) {
            lbl_boasVindas.setText("Bom Dia");
        } else if (hora > 12 && hora < 18) {
            lbl_boasVindas.setText("Boa Tarde");
        } else {
            lbl_boasVindas.setText("Boa Noite");
        }

    }


    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            System.out.println(" Bem vindo");
        }

    }//GEN-LAST:event_formKeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged

    }//GEN-LAST:event_formWindowStateChanged

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentResized
    /**
     * @param args the command line arguments
     */

    public void inicializar() {
        try {
            for (int i = 0; i <= 100; i++) {
                JProgressBar.setValue(0);
                JProgressBar.setValue(i);
                jLabel8.setText(Integer.toString(i) + "%");
                Thread.sleep(100);
                if (i < 20) {
                    lbl_texto.setText(" A processar..");
                    lbl_imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Jail_ts2022/icons/criminal-running-with-stolen-woman-bag.png")));
//                   
                } else if (i < 35) {
                    lbl_texto.setText(" Aguarde...");
                    lbl_imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Jail_ts2022/icons/robber-silhouette-trying-to-steal-car-part.png")));
//                  
                } else if (i < 65) {
                    lbl_imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Jail_ts2022/icons/violent-criminal.png")));
//                   
                } else if (i < 85) {
                    lbl_texto.setText(" Aguarde...");
                    lbl_imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Jail_ts2022/icons/criminal-pointing-a-gun-to-a-victim-on-the-floor.png")));
//                   
                } else if (i < 90) {
                    lbl_texto.setText(" A processar....");
                    lbl_imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Jail_ts2022/icons/criminal-posing-for-police-picture.png")));
//                  
                } else if (i == 99) {
                    lbl_texto.setText(" Concluido.");

                }
            }
            VerificarUsuarios();
        } catch (InterruptedException e) {
        }
    }

    public void VerificarUsuarios() {

        String querySql = "select* from  tbfuncionario"; //conta os registros 
        try {
            stat = conexao.prepareStatement(querySql);
            rst = stat.executeQuery();

            if (!rst.next()) {
                this.dispose();
                new TelaRegistoDirector().setVisible(true);
            } else {
                this.dispose();
                new TelaLogin().setVisible(true);
            }

        } catch (Exception e) {
            lbl_imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Jail_ts2022/icons/erroc.png")));
        }

    }

    private String dataf;
    private SimpleDateFormat sdf;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JProgressBar JProgressBar;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel lbl_Conexao;
    public javax.swing.JLabel lbl_boasVindas;
    public javax.swing.JLabel lbl_horaData;
    public javax.swing.JLabel lbl_imagem;
    private javax.swing.JLabel lbl_texto;
    // End of variables declaration//GEN-END:variables
  public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(recuperarConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(recuperarConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(recuperarConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(recuperarConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        CaregarOPrograma loading = new CaregarOPrograma();
        loading.setVisible(true);
        loading.inicializar();

    }

    private void setIconImage() {
        URL url = this.getClass().getResource("/Jail_ts2022/icons/prisoner.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(iconeTitulo);
    }
}
