/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Jail_ts2022.views;

import Jail_ts2022.conexao.Conectar;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.YearMonth;
import java.util.Arrays;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.regex.Pattern;
import javax.swing.BorderFactory;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Jail_ts2022.dao.CelasDao;
import Jail_ts2022.dao.CrimesDAo;
import Jail_ts2022.dao.EnderecoDAo;
import Jail_ts2022.dao.NacionalidadeDao;
import Jail_ts2022.dao.ProvinciasDAo;
import Jail_ts2022.dao.ReclusoDao;
import Jail_ts2022.model.Celas;
import Jail_ts2022.model.Crimes;
import Jail_ts2022.model.Endereco;
import Jail_ts2022.model.Formatador;
import Jail_ts2022.model.Funcionario;
import Jail_ts2022.model.Nacionalidade;
import Jail_ts2022.model.Recluso;
import Jail_ts2022.model.Provincias;
import java.text.DateFormat;
import java.util.ArrayList;
import javax.swing.JLabel;

/**
 *
 * @author Mutisse
 */
public final class RegistarDeRecluso extends javax.swing.JInternalFrame {

    Funcionario funcionarioLogado = new Funcionario();

    public void setUsuarioActual(Funcionario funcionarioLogado) {
        this.funcionarioLogado = funcionarioLogado;
    }

    public JLabel getLbl_idFuncionaio() {
        return lbl_idFuncionaio;
    }

    public RegistarDeRecluso() {
        initComponents();
        //
        PrencherTabela();
        celasCb();
        jList_crimes.setModel(modelListCrimes);
        dseabilitar();
        mostrarPesqisa();

    }

    void dseabilitar() {
        btn_atualizar.setEnabled(false);
        btn_eliminar.setEnabled(false);
        //btn_salvar.setEnabled(false);
        jList1.setVisible(false);
        jList1.setModel(modelo);
        lbl_idFuncionaio.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    /* ****************************** metodo setar campos **********************/
 /*
     Nesses espaços vão estar registrados os seguintes métodos salvar,editar,remover, pesquisa avançada ,
     preencher tabelas combox, preencher os campos para edição e remoção etc 
     */
    public void FormatDatachoos() {
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        String data = sdf.format(Calendar.getInstance().getTime());
        try {
            JDataFormatada.setDate(sdf.parse(data));
            JDataFormatada.setMaxSelectableDate(sdf.parse(data));

        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Erro na conversão da data!");
        }
    }
// ------------------- preencher as celas --------------

    void naturaluadeCb() {

        for (int i = 0; i < listarNacionalidade.size(); i++) {

            cb_naturalidade.addItem(listarNacionalidade.get(i));

        }

    }

    void celasCb() {
        cb_celas.removeAllItems();
        for (int i = 0; i < listarCelas.size(); i++) {
            cb_celas.addItem(listarCelas.get(i));
        }
    }

    void listarPesquisa() {

        try {
            conexao = Conectar.conector();
            String querySql = "SELECT * from tbrecluso LEFT JOIN tbrecluso_has_tbcrimes on tbrecluso.id_recluso=tbrecluso_has_tbcrimes.tbrecluso_id_recluso LEFT JOIN tbcrimes on tbcrimes.id_crimes= tbrecluso_has_tbcrimes.tbcrimes_id_crimes LEFT join tbendereco on tbendereco.id_endereco=tbrecluso.id_recluso LEFT JOIN tbprovincias on tbendereco.tbprovincias_id_Provincias= tbprovincias.id_Provincias LEFT JOIN tbnacionalidade on tbnacionalidade.id_nacionalidade=tbprovincias.tbnacionalidade_id_nacionalidade LEFT JOIN tbcelas on tbcelas.id_celas=tbrecluso.tbcelas_id_celas WHERE  nome like?  and StatusRecluso != 'Removido'  order by nome;";

            stat = conexao.prepareStatement(querySql);
            stat.setString(1, txt_pesquisar.getText() + "%");
            rst = stat.executeQuery();
            int i = 0;

            if (rst.next() & i < 5) {

                modelo.addElement(rst.getString("nome") + " " + rst.getString("apelido"));
                index[i] = rst.getString("id_recluso");
                i++;
                // prenchera pesquisa
                lbl_idregistro.setText(rst.getString("id_recluso"));
                lbl_Codigo.setText(rst.getString("codigoDeRrcluso"));
                txt_Nome.setText(rst.getString("nome"));
                txt_Apelido.setText(rst.getString("apelido"));
                txt_NumeroDeBI.setText(rst.getString("nrbi"));
                lbl_frequecia.setText(rst.getString("frequencia"));
                lbl_penaDefinida.setText(rst.getString("duracaoDapena"));

                DateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
                Date date = (Date) formatter.parse(String.valueOf(rst.getDate("datadeNascimento")));
                JDataFormatada.setDate(date);
                if (rst.getString("genero").equalsIgnoreCase("Masculino")) {
                    rb_Masculino.isSelected();
                } else {
                    rb_Feminino.isSelected();
                }

                cb_nivelAcadademico.setSelectedItem("nivelAcademico");
                cb_doencas.setSelectedItem("doenca");
                cb_naturalidade.setSelectedItem("nomeDoPais");
                cb_provincias.setSelectedItem("NomeDaProvincia");
                cb_EstadoDePrisao.setSelectedItem("estadoDePrisao");
                cb_celas.setSelectedItem("NomeDacela");
                lbl_cama.setText("nrcama");

                lbl_idregistro1.setText(rst.getString("nome"));
                txt_rua.setText(rst.getString("rua"));
                txt_bairro.setText(rst.getString("bairro"));
                txt_quarteirao.setText(rst.getString("quarteirao"));
                txt_nCasa.setText(rst.getString("casa"));

                txtA_bens.setText(rst.getString("registroDeBens"));
                jlist_caracterizar.setText(rst.getString("caracterizar"));

                modelListCrimes.addElement("categoriaDeCrime");

            }
            if (i >= 1) {
                jList1.setVisible(true);
            } else {
                jList1.setVisible(false);
            }

        } catch (Exception e) {
            System.out.println(e);
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e + " Erro ao buscar o registro", "Notificação", JOptionPane.ERROR);
        } finally {
            try {
                stat.close();
                conexao.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e + "Erro na conexao");

            }
        }

    }

    void mostrarPesqisa() {
        int linha = jList1.getSelectedIndex();
        if (linha >= 0) {
            String querySql = "select * from tbrecluso where id_recluso=" + index[linha] + "";
            reclusaoDAo.listarTodosReclusos();
        }
    }

    /* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Setar campos    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   esse metodo vai prencher os campos  de formulario funcionario com falaores perenchidos na tabela 
     */
    void FrequeciasDeprisao() {
        if (reclusaoDAo.verificarAfrequeciasDeRcluso(txt_NumeroDeBI.getText(), txt_Nome.getText(), txt_Apelido.getText()) == true) {
            JOptionPane.showMessageDialog(null, " O Recluso que esta a registar foi ativado por ja ter a pasado deta peniteciaria.\n atualize a sua pena.", "", JOptionPane.OK_OPTION);
            jTabbedPane.setSelectedIndex(1);
        } else {
            JOptionPane.showMessageDialog(rootPane, " nao enconrado");
        }

    }
    //----------------------------------------------------------

    void Setarcodigo() {

        String str = String.valueOf(reclusaoDAo.GerarCodigo());
        Date data = new Date();
        SimpleDateFormat formatarD = new SimpleDateFormat("MM");
        // int mesDeEntrada = Integer.parseInt();
        lbl_Codigo.setText(String.valueOf(str + "" + formatarD.format(data) + "" + YearMonth.now().getYear()));
    }

    public void PrencherTabela() {
        try {

            List<Recluso> Lista = reclusaoDAo.listarTodosReclusos();
            DefaultTableModel newModelTable = (DefaultTableModel) tb_recluso.getModel();
            newModelTable.setRowCount(0);

            Lista.forEach((Recluso Usuario) -> {
                if (!"Solto".equalsIgnoreCase(Usuario.getEstado())) {
                    if ((!"removido".equalsIgnoreCase(Usuario.getEstado()))) {
//                        if ((Usuario.getCrime().equals(listaCrimes))) {
//                            crimesCometidos=crime.getCategoriaDeCrime();
//                                System.out.println(" TAble"+crimesCometidos);
//                                
//                            }

                        newModelTable.addRow(new Object[]{Usuario.getCodigo(), Usuario.getNome() + " " + Usuario.getApelido(),
                            Usuario.getGenero(), Usuario.getCrime().toString(), Usuario.getDuracaoDapena(), Usuario.getCelas().getCela(), Usuario.getCelas().getNrcama(),
                            Usuario.getEstadoDaPrisao(), Usuario.getFrequencia()

                        });
// }
//                        for (int i = 0; i < Usuario.getCrime().size(); i++) {
//                            System.out.println(Usuario.getCrime().get(i).getCategoriaDeCrime());
//                        }

// , Usuario.getAdvogado().getNomeDeAdvogado()
                    }
                }
            });
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage() + " Erro ao preencher atabela ", "Notificação", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void sett_campos() {
        //  ControllerFuncionario Desesctpg = new ControllerFuncionario(); Desesctpg.DesEmcriptar()
        try {
            int setar = tb_recluso.getSelectedRow();

            List<Recluso> Lista = reclusaoDAo.listarTodosReclusos();
            for (Recluso prisioneiro : Lista) {

                if (tb_recluso.getModel().getValueAt(setar, 0).toString().equals(prisioneiro.getCodigo())) {

                  //  if (prisioneiro.getEstado().equalsIgnoreCase("Activo")) {

                        lbl_Codigo.setText(prisioneiro.getCodigo());
                        txt_Nome.setText(prisioneiro.getNome());
                        txt_Apelido.setText(prisioneiro.getApelido());
                        cb_provincias.setSelectedItem(prisioneiro.getEndereco().getProvincias());
                        cb_provincias.setSelectedItem(prisioneiro.getEndereco().getProvincias().getNacionalidade());
                        txt_rua.setText(prisioneiro.getEndereco().getRua());
                        txt_bairro.setText(prisioneiro.getEndereco().getCasa());
                        txt_nCasa.setText(prisioneiro.getEndereco().getRua());
                        txt_quarteirao.setText(prisioneiro.getEndereco().getQuarteirao());
                        txt_NumeroDeBI.setText(prisioneiro.getNumeroDeBI());
                        if (prisioneiro.getGenero().equals("Masculino")) {
                            rb_Masculino.setSelected(true);
                        } else if (prisioneiro.getGenero().equals("Feminino")) {
                            rb_Feminino.setSelected(true);
                        }

                        txt_NumeroDeBI.setText(prisioneiro.getNumeroDeBI());
                        // endereco
                        txt_rua.setText(prisioneiro.getEndereco().getRua());
                        txt_bairro.setText(prisioneiro.getEndereco().getCasa());
                        txt_nCasa.setText(prisioneiro.getEndereco().getRua());
                        txt_quarteirao.setText(prisioneiro.getEndereco().getQuarteirao());
                        cb_provincias.setSelectedItem(prisioneiro.getEndereco().getProvincias());
                        cb_provincias.setSelectedItem(prisioneiro.getEndereco().getProvincias().getNacionalidade());
                        //cb_nivelAcadademico.setText(prisioneiro.getNivelAcademico());
                        
                        // txt_rua.setText(prisioneiro.getEndereco().getRua());

//                        tf_contacto.setText(prisioneiro.getContacto());
//                        txt_email.setText(prisioneiro.getEmail());
//                        pf_Senha.setText(prisioneiro.getSenha());
//                        
                        cb_nivelAcadademico.setSelectedItem(prisioneiro.getNivelAcademico());
                        cb_doencas.setSelectedItem(prisioneiro.getNivelAcademico());

                        DateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
                        Date date = (Date) formatter.parse(prisioneiro.getDatadeNascimento());
                        JDataFormatada.setDate(date);

                  //  }

                }
            }

        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, e + " Erro!! Campo Selecionado esta vazio", "Notificação", JOptionPane.ERROR);
        }

    }

    void reclusoExistente() {
        int contt = 0;
        for (int i = 0; i < tb_recluso.getRowCount(); i++) {
            if (txt_NumeroDeBI.getText().equals(tb_recluso.getModel().getValueAt(i, 5))) {
                contt = 1;
            }

        }

        if (contt >= 1) {
            JOptionPane.showMessageDialog(null, "Este funcionário já existe", "Notificação ", JOptionPane.WARNING_MESSAGE);
        }

    }

    void validarVcampos() {

        if (txt_Nome.getText().isEmpty()) {
            btn_proximo.setEnabled(false);
            JOptionPane.showMessageDialog(null, "O Campo  Nome deve Ser Preenchido!", "Atenção", JOptionPane.WARNING_MESSAGE);
        } else if (txt_Nome.getText().isEmpty()) {
            btn_proximo.setEnabled(false);
            JOptionPane.showMessageDialog(null, "O Campo Apelido Deve  Ser Preenchido!", "Atenção", JOptionPane.WARNING_MESSAGE);
        } else if (txt_NumeroDeBI.getText().isEmpty()) {
            btn_proximo.setEnabled(false);
            JOptionPane.showMessageDialog(null, "O Campo Número de BI Deve Ser Preenchido!", "Atenção", JOptionPane.WARNING_MESSAGE);
        } else if (cb_provincias.getActionCommand().isEmpty()) {
            btn_proximo.setEnabled(false);
            JOptionPane.showMessageDialog(null, "Não foi seleccionada nenhuma Categoria!", "Atenção", JOptionPane.WARNING_MESSAGE);
        } else if (cb_crimes.getActionCommand().isEmpty()) {
            btn_proximo.setEnabled(false);
            JOptionPane.showMessageDialog(null, "Não foi seleccionado nenhum crime, por favor Informe um crime.", "Atenção", JOptionPane.WARNING_MESSAGE);
        } else if (cb_EstadoDePrisao.getActionCommand().isEmpty()) {
            btn_proximo.setEnabled(false);
            JOptionPane.showMessageDialog(null, "Não foi seleccionado nenhum estado, por favor Informe  um estado do prisioneiro.", "Atenção", JOptionPane.WARNING_MESSAGE);
        } else if (cb_celas.getActionCommand().isEmpty()) {
            btn_proximo.setEnabled(false);
            JOptionPane.showMessageDialog(null, "Por favor informe uma cela ao prisioneiro.", "Atenção", JOptionPane.WARNING_MESSAGE);
        } else {
            btn_proximo.setEnabled(true);
            table1Registrar();
        }
    }


    /* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ limpar campos    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  */
    public void LimparCampos() {
        txt_Nome.setText(null);
        lbl_idregistro.setText(null);
        txt_Apelido.setText(null);
        txt_NumeroDeBI.setText(null);
        lbl_Codigo.setText(null);
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();
        cb_provincias.setSelectedIndex(-1);
        cb_EstadoDePrisao.setSelectedIndex(-1);
        cb_nivelAcadademico.setSelectedIndex(-1);
        btn_foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Jail_ts2022/icons/prisoner.png")));

    }

    /* ****************************** Eventos  **********************/
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jTabbedPane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        txt_pesquisar = new javax.swing.JTextField();
        jList1 = new javax.swing.JList<>();
        jPanel4 = new javax.swing.JPanel();
        JDataFormatada = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        rb_Feminino = new javax.swing.JRadioButton();
        txt_NumeroDeBI = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        rb_Masculino = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_Apelido = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        btn_foto = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        lbl_Codigo = new javax.swing.JLabel();
        txt_Nome = new javax.swing.JTextField();
        lbl_idregistro = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        cb_doencas = new javax.swing.JComboBox<>();
        cb_nivelAcadademico = new javax.swing.JComboBox<>();
        jLabel34 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lbl_frequecia = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btn_Limpar2 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        btn_proximo = new javax.swing.JButton();
        cb_naturalidade = new javax.swing.JComboBox<>();
        jLabel44 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        cb_provincias = new javax.swing.JComboBox<>();
        txt_bairro = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        txt_quarteirao = new javax.swing.JTextField();
        txt_nCasa = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txt_rua = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lbl_idFuncionaio = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_recluso = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        cb_EstadoDePrisao = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtA_bens = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList_crimes = new javax.swing.JList<>();
        lbl_penaDefinida = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        lbl_duracaoEmAno = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        cb_crimes = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        lbl_duracaoEmMeses = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbl_nuemroDecamasEcapacidadeMaxima = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cb_celas = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lbl_cama = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jlist_caracterizar = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();
        btn_salvar1 = new javax.swing.JButton();
        btn_atualizar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        lbl_idregistro1 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(214, 217, 223));
        setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray));
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Registrar Recluso ");
        setMinimumSize(new java.awt.Dimension(897, 606));
        setPreferredSize(new java.awt.Dimension(897, 610));
        getContentPane().setLayout(null);

        jTabbedPane.setBackground(new java.awt.Color(204, 204, 204));
        jTabbedPane.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTabbedPane.setForeground(new java.awt.Color(153, 153, 153));
        jTabbedPane.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTabbedPane.setMinimumSize(new java.awt.Dimension(897, 606));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel1KeyPressed(evt);
            }
        });
        jPanel1.setLayout(null);

        txt_pesquisar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_pesquisar.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        txt_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pesquisarActionPerformed(evt);
            }
        });
        txt_pesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_pesquisarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_pesquisarKeyReleased(evt);
            }
        });
        jPanel1.add(txt_pesquisar);
        txt_pesquisar.setBounds(10, 5, 240, 30);

        jList1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray));
        jList1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jList1KeyReleased(evt);
            }
        });
        jPanel1.add(jList1);
        jList1.setBounds(10, 35, 240, 128);

        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setOpaque(false);
        jPanel4.setLayout(null);

        JDataFormatada.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        JDataFormatada.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel4.add(JDataFormatada);
        JDataFormatada.setBounds(570, 100, 160, 30);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("* Nome:");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(250, 70, 90, 20);

        buttonGroup1.add(rb_Feminino);
        rb_Feminino.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rb_Feminino.setText("Feminino");
        rb_Feminino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_FemininoActionPerformed(evt);
            }
        });
        jPanel4.add(rb_Feminino);
        rb_Feminino.setBounds(830, 150, 110, 30);

        txt_NumeroDeBI.setBackground(new java.awt.Color(240, 240, 240));
        txt_NumeroDeBI.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        try {
            txt_NumeroDeBI.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("############*")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_NumeroDeBI.setEnabled(false);
        txt_NumeroDeBI.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_NumeroDeBI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_NumeroDeBIKeyPressed(evt);
            }
        });
        jPanel4.add(txt_NumeroDeBI);
        txt_NumeroDeBI.setBounds(570, 160, 160, 30);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Género:");
        jPanel4.add(jLabel2);
        jLabel2.setBounds(830, 80, 50, 20);

        buttonGroup1.add(rb_Masculino);
        rb_Masculino.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rb_Masculino.setText("Masculino");
        rb_Masculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_MasculinoActionPerformed(evt);
            }
        });
        jPanel4.add(rb_Masculino);
        rb_Masculino.setBounds(830, 120, 110, 30);

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Data de Nascimento:");
        jPanel4.add(jLabel16);
        jLabel16.setBounds(570, 70, 140, 20);

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Número de BI:");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(570, 140, 120, 20);

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("* Apelido:");
        jPanel4.add(jLabel12);
        jLabel12.setBounds(250, 140, 90, 20);

        jLabel9.setBackground(new java.awt.Color(204, 204, 204));
        jLabel9.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));
        jPanel4.add(jLabel9);
        jLabel9.setBounds(820, 110, 140, 80);

        txt_Apelido.setBackground(new java.awt.Color(240, 240, 240));
        txt_Apelido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_Apelido.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        txt_Apelido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_ApelidoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_ApelidoKeyTyped(evt);
            }
        });
        jPanel4.add(txt_Apelido);
        txt_Apelido.setBounds(250, 160, 260, 30);

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setLayout(null);

        btn_foto.setBackground(new java.awt.Color(204, 204, 204));
        btn_foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Jail_ts2022/icons/prisoner.png"))); // NOI18N
        btn_foto.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white)));
        jPanel5.add(btn_foto);
        btn_foto.setBounds(20, 60, 150, 160);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Código ");
        jPanel5.add(jLabel10);
        jLabel10.setBounds(20, 20, 50, 20);

        lbl_Codigo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_Codigo.setForeground(new java.awt.Color(255, 0, 51));
        lbl_Codigo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Codigo.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        jPanel5.add(lbl_Codigo);
        lbl_Codigo.setBounds(70, 20, 100, 25);

        jPanel4.add(jPanel5);
        jPanel5.setBounds(20, 50, 190, 240);

        txt_Nome.setBackground(new java.awt.Color(240, 240, 240));
        txt_Nome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_Nome.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        txt_Nome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_NomeKeyPressed(evt);
            }
        });
        jPanel4.add(txt_Nome);
        txt_Nome.setBounds(250, 100, 260, 30);

        lbl_idregistro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_idregistro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_idregistro.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        jPanel4.add(lbl_idregistro);
        lbl_idregistro.setBounds(160, 20, 50, 25);

        jLabel29.setBackground(new java.awt.Color(255, 255, 255));
        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(51, 51, 51));
        jLabel29.setText("Frequencia");
        jPanel4.add(jLabel29);
        jLabel29.setBounds(890, 20, 50, 20);

        cb_doencas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cb_doencas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nenhuma ", "Hiv/Sida", "Diabetes", "Asma", "Tensao", "Sindrome de panico", "Tronbose", " " }));
        jPanel4.add(cb_doencas);
        cb_doencas.setBounds(420, 250, 120, 30);

        cb_nivelAcadademico.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cb_nivelAcadademico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Basico", "Medio", "Superior" }));
        cb_nivelAcadademico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_nivelAcadademicoActionPerformed(evt);
            }
        });
        jPanel4.add(cb_nivelAcadademico);
        cb_nivelAcadademico.setBounds(250, 250, 130, 30);

        jLabel34.setBackground(new java.awt.Color(255, 255, 255));
        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(51, 51, 51));
        jLabel34.setText("Nível Académico:     ");
        jPanel4.add(jLabel34);
        jLabel34.setBounds(250, 220, 110, 20);

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setText(" Doença ");
        jPanel4.add(jLabel18);
        jLabel18.setBounds(420, 220, 100, 20);

        lbl_frequecia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_frequecia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_frequecia.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        jPanel4.add(lbl_frequecia);
        lbl_frequecia.setBounds(960, 20, 60, 30);

        jLabel36.setBackground(new java.awt.Color(255, 255, 255));
        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(51, 51, 51));
        jLabel36.setText("Numero de registro");
        jPanel4.add(jLabel36);
        jLabel36.setBounds(20, 30, 96, 14);

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray), "*campos Obrigatorios ", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 3, 12))); // NOI18N
        jPanel4.add(jLabel3);
        jLabel3.setBounds(220, 60, 810, 145);

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));
        jPanel4.add(jLabel1);
        jLabel1.setBounds(10, 10, 1030, 290);

        btn_Limpar2.setBackground(new java.awt.Color(204, 255, 255));
        btn_Limpar2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_Limpar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Jail_ts2022/icons/clean.png"))); // NOI18N
        btn_Limpar2.setText("Limpar");
        btn_Limpar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Limpar2ActionPerformed(evt);
            }
        });
        btn_Limpar2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_Limpar2KeyPressed(evt);
            }
        });
        jPanel4.add(btn_Limpar2);
        btn_Limpar2.setBounds(830, 250, 160, 31);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(10, 40, 1050, 310);

        jPanel6.setLayout(null);

        btn_proximo.setBackground(new java.awt.Color(204, 255, 255));
        btn_proximo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_proximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Jail_ts2022/icons/add1.png"))); // NOI18N
        btn_proximo.setText("Proximo Formulario");
        btn_proximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_proximoActionPerformed(evt);
            }
        });
        btn_proximo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_proximoKeyPressed(evt);
            }
        });
        jPanel6.add(btn_proximo);
        btn_proximo.setBounds(700, 120, 270, 33);

        cb_naturalidade.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cb_naturalidade.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_naturalidadeItemStateChanged(evt);
            }
        });
        jPanel6.add(cb_naturalidade);
        cb_naturalidade.setBounds(40, 60, 200, 30);

        jLabel44.setBackground(new java.awt.Color(255, 255, 255));
        jLabel44.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(51, 51, 51));
        jLabel44.setText("Naturaldade:");
        jPanel6.add(jLabel44);
        jLabel44.setBounds(40, 40, 70, 14);

        jLabel27.setBackground(new java.awt.Color(255, 255, 255));
        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(51, 51, 51));
        jLabel27.setText("* Provicia");
        jPanel6.add(jLabel27);
        jLabel27.setBounds(40, 104, 80, 20);

        cb_provincias.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cb_provincias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_provinciasActionPerformed(evt);
            }
        });
        jPanel6.add(cb_provincias);
        cb_provincias.setBounds(40, 130, 200, 30);

        txt_bairro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_bairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_bairroActionPerformed(evt);
            }
        });
        txt_bairro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_bairroKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_bairroKeyTyped(evt);
            }
        });
        jPanel6.add(txt_bairro);
        txt_bairro.setBounds(300, 130, 110, 30);

        jLabel39.setBackground(new java.awt.Color(255, 255, 255));
        jLabel39.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(51, 51, 51));
        jLabel39.setText("Bairro");
        jPanel6.add(jLabel39);
        jLabel39.setBounds(300, 100, 40, 20);

        txt_quarteirao.setDocument(new Formatador(4, Formatador.TipoEntrada.NUMERO_INTEIRO));
        txt_quarteirao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_quarteirao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_quarteiraoActionPerformed(evt);
            }
        });
        txt_quarteirao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_quarteiraoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_quarteiraoKeyTyped(evt);
            }
        });
        jPanel6.add(txt_quarteirao);
        txt_quarteirao.setBounds(430, 130, 50, 30);

        txt_nCasa.setDocument(new Formatador(5, Formatador.TipoEntrada.NUMERO_INTEIRO));
        txt_nCasa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_nCasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nCasaActionPerformed(evt);
            }
        });
        txt_nCasa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_nCasaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nCasaKeyTyped(evt);
            }
        });
        jPanel6.add(txt_nCasa);
        txt_nCasa.setBounds(500, 130, 50, 30);

        jLabel37.setBackground(new java.awt.Color(255, 255, 255));
        jLabel37.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(51, 51, 51));
        jLabel37.setText("N ° casa");
        jPanel6.add(jLabel37);
        jLabel37.setBounds(500, 100, 40, 20);

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 51, 51));
        jLabel22.setText("Quateirao  ");
        jPanel6.add(jLabel22);
        jLabel22.setBounds(430, 100, 52, 20);

        txt_rua.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_rua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ruaActionPerformed(evt);
            }
        });
        txt_rua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_ruaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_ruaKeyTyped(evt);
            }
        });
        jPanel6.add(txt_rua);
        txt_rua.setBounds(300, 60, 250, 30);

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Av/Rua");
        jPanel6.add(jLabel14);
        jLabel14.setBounds(300, 40, 40, 20);

        jLabel31.setBackground(new java.awt.Color(204, 204, 204));
        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel31.setText(" ");
        jLabel31.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Local de Residencia ", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 10))); // NOI18N
        jPanel6.add(jLabel31);
        jLabel31.setBounds(20, 20, 560, 160);

        jPanel1.add(jPanel6);
        jPanel6.setBounds(10, 360, 1045, 210);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Jail_ts2022/icons/Pesq.png"))); // NOI18N
        jPanel1.add(jLabel23);
        jLabel23.setBounds(260, 10, 30, 30);
        jPanel1.add(lbl_idFuncionaio);
        lbl_idFuncionaio.setBounds(960, 10, 90, 25);

        jTabbedPane.addTab("Dados pessoais", jPanel1);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(null);

        tb_recluso = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIdex){
                return false;
            }
        };
        tb_recluso.setBackground(new java.awt.Color(204, 204, 204));
        tb_recluso.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tb_recluso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome completo", "Genero", "Crimes", "ano de siada", "Cela", "cama", "estado da Prisao", "frequencia", "Nome de Advogado"
            }
        ));
        tb_recluso.setMinimumSize(new java.awt.Dimension(897, 606));
        tb_recluso.setPreferredSize(new java.awt.Dimension(897, 606));
        tb_recluso.setShowHorizontalLines(false);
        tb_recluso.setShowVerticalLines(false);
        tb_recluso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_reclusoMouseClicked(evt);
            }
        });
        tb_recluso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tb_reclusoKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tb_recluso);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 400, 1040, 150);

        jPanel3.setLayout(null);

        jPanel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        jPanel7.setLayout(null);

        cb_EstadoDePrisao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cb_EstadoDePrisao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "condenado", "espera de julgamento" }));
        cb_EstadoDePrisao.setSelectedIndex(-1);
        cb_EstadoDePrisao.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_EstadoDePrisaoItemStateChanged(evt);
            }
        });
        jPanel7.add(cb_EstadoDePrisao);
        cb_EstadoDePrisao.setBounds(260, 50, 160, 30);

        jLabel26.setBackground(new java.awt.Color(255, 255, 255));
        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(51, 51, 51));
        jLabel26.setText("*Estado de Criminoso:");
        jPanel7.add(jLabel26);
        jLabel26.setBounds(260, 20, 120, 20);

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setText("Registro de  bens     ");
        jPanel7.add(jLabel19);
        jLabel19.setBounds(30, 140, 160, 20);

        txtA_bens.setColumns(20);
        txtA_bens.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtA_bens.setRows(5);
        txtA_bens.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray));
        jPanel7.add(txtA_bens);
        txtA_bens.setBounds(30, 170, 180, 100);

        jList_crimes.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray));
        jList_crimes.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jList_crimes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList_crimesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jList_crimes);

        jPanel7.add(jScrollPane2);
        jScrollPane2.setBounds(260, 160, 160, 110);

        lbl_penaDefinida.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lbl_penaDefinida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_penaDefinida.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray));
        lbl_penaDefinida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_penaDefinidaMouseEntered(evt);
            }
        });
        jPanel7.add(lbl_penaDefinida);
        lbl_penaDefinida.setBounds(440, 190, 140, 30);

        jLabel38.setBackground(new java.awt.Color(255, 255, 255));
        jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(51, 51, 51));
        jLabel38.setText("Ano de saida ");
        jPanel7.add(jLabel38);
        jLabel38.setBounds(440, 160, 100, 20);

        lbl_duracaoEmAno.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_duracaoEmAno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_duracaoEmAno.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        jPanel7.add(lbl_duracaoEmAno);
        lbl_duracaoEmAno.setBounds(440, 250, 60, 30);

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel35.setText("Anos");
        jPanel7.add(jLabel35);
        jLabel35.setBounds(440, 230, 40, 20);

        cb_crimes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cb_crimes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_crimesItemStateChanged(evt);
            }
        });
        cb_crimes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cb_crimesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cb_crimesMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cb_crimesMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cb_crimesMouseReleased(evt);
            }
        });
        cb_crimes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_crimesActionPerformed(evt);
            }
        });
        cb_crimes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cb_crimesKeyPressed(evt);
            }
        });
        jPanel7.add(cb_crimes);
        cb_crimes.setBounds(260, 120, 160, 30);

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 51, 51));
        jLabel24.setText("*Crime Cometido:");
        jPanel7.add(jLabel24);
        jLabel24.setBounds(260, 90, 110, 30);

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel28.setText("Meses   ");
        jPanel7.add(jLabel28);
        jLabel28.setBounds(520, 230, 40, 20);

        lbl_duracaoEmMeses.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_duracaoEmMeses.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_duracaoEmMeses.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        jPanel7.add(lbl_duracaoEmMeses);
        lbl_duracaoEmMeses.setBounds(520, 250, 60, 30);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Capacidade maxima e camas diponivies ");
        jPanel7.add(jLabel8);
        jLabel8.setBounds(680, 10, 230, 20);

        lbl_nuemroDecamasEcapacidadeMaxima.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        lbl_nuemroDecamasEcapacidadeMaxima.setForeground(new java.awt.Color(255, 0, 0));
        lbl_nuemroDecamasEcapacidadeMaxima.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel7.add(lbl_nuemroDecamasEcapacidadeMaxima);
        lbl_nuemroDecamasEcapacidadeMaxima.setBounds(920, 10, 40, 20);

        jLabel7.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray));
        jPanel7.add(jLabel7);
        jLabel7.setBounds(690, 150, 220, 30);

        cb_celas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cb_celas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_celasActionPerformed(evt);
            }
        });
        cb_celas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cb_celasKeyPressed(evt);
            }
        });
        jPanel7.add(cb_celas);
        cb_celas.setBounds(690, 100, 80, 30);

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("*Celas");
        jPanel7.add(jLabel15);
        jLabel15.setBounds(690, 70, 60, 20);

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setText("Cama");
        jPanel7.add(jLabel17);
        jLabel17.setBounds(850, 70, 60, 20);

        lbl_cama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_cama.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray));
        jPanel7.add(lbl_cama);
        lbl_cama.setBounds(850, 100, 60, 30);

        jLabel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.add(jLabel6);
        jLabel6.setBounds(640, 40, 350, 160);

        jlist_caracterizar.setColumns(20);
        jlist_caracterizar.setFont(new java.awt.Font("Segoe UI", 3, 11)); // NOI18N
        jlist_caracterizar.setRows(5);
        jlist_caracterizar.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray));
        jPanel7.add(jlist_caracterizar);
        jlist_caracterizar.setBounds(30, 50, 180, 80);

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 51, 51));
        jLabel20.setText(" Caracterizar   o Recluso");
        jPanel7.add(jLabel20);
        jLabel20.setBounds(30, 20, 150, 16);

        btn_salvar1.setBackground(new java.awt.Color(204, 255, 255));
        btn_salvar1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_salvar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Jail_ts2022/icons/add.png"))); // NOI18N
        btn_salvar1.setText("Registar");
        btn_salvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvar1ActionPerformed(evt);
            }
        });
        jPanel7.add(btn_salvar1);
        btn_salvar1.setBounds(840, 250, 150, 31);

        btn_atualizar.setBackground(new java.awt.Color(204, 255, 255));
        btn_atualizar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_atualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Jail_ts2022/icons/atualizar.png"))); // NOI18N
        btn_atualizar.setText("Editar");
        btn_atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atualizarActionPerformed(evt);
            }
        });
        btn_atualizar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_atualizarKeyPressed(evt);
            }
        });
        jPanel7.add(btn_atualizar);
        btn_atualizar.setBounds(640, 250, 160, 31);

        btn_eliminar.setBackground(new java.awt.Color(204, 255, 255));
        btn_eliminar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Jail_ts2022/icons/remov.png"))); // NOI18N
        btn_eliminar.setText("Remover");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });
        btn_eliminar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_eliminarKeyPressed(evt);
            }
        });
        jPanel7.add(btn_eliminar);
        btn_eliminar.setBounds(640, 210, 160, 31);

        jPanel3.add(jPanel7);
        jPanel7.setBounds(10, 50, 1010, 290);

        lbl_idregistro1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_idregistro1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_idregistro1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        jPanel3.add(lbl_idregistro1);
        lbl_idregistro1.setBounds(150, 10, 50, 25);

        jLabel40.setBackground(new java.awt.Color(255, 255, 255));
        jLabel40.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(51, 51, 51));
        jLabel40.setText("Numero de registro");
        jPanel3.add(jLabel40);
        jLabel40.setBounds(15, 15, 100, 14);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(10, 20, 1040, 360);

        jTabbedPane.addTab("Dados de Recluso", jPanel2);

        getContentPane().add(jTabbedPane);
        jTabbedPane.setBounds(0, 0, 1070, 610);

        setBounds(0, 0, 1072, 640);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyPressed
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_UP:
                txt_Nome.requestFocus();
                break;
            case KeyEvent.VK_DOWN:
                rb_Masculino.requestFocus();
                break;

            default:
                break;
        }
    }//GEN-LAST:event_jPanel1KeyPressed

    private void btn_proximoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_proximoKeyPressed
        switch (evt.getKeyCode()) {

            case KeyEvent.VK_LEFT:
                btn_atualizar.requestFocus();
                break;

            case KeyEvent.VK_UP:
//                tA_registroDeBens.requestFocus();
                break;

        }
    }//GEN-LAST:event_btn_proximoKeyPressed

    private void btn_proximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_proximoActionPerformed
        jTabbedPane.setSelectedIndex(1);
    }//GEN-LAST:event_btn_proximoActionPerformed

    private void btn_atualizarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_atualizarKeyPressed
        switch (evt.getKeyCode()) {

            case KeyEvent.VK_LEFT:
                btn_eliminar.requestFocus();
                break;
            case KeyEvent.VK_RIGHT:
                btn_proximo.requestFocus();
                break;

        }
    }//GEN-LAST:event_btn_atualizarKeyPressed

    private void btn_atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atualizarActionPerformed
        if (btn_atualizar.getText().equalsIgnoreCase("Editar")) {
            btn_atualizar.setText("Atualizar");

        } else {
            btn_atualizar.setText("Editar");
            Atualizar();
        }

//   Atualizar     int resposta = JOptionPane.showConfirmDialog(null, " Vai registrar uma Advogado?", "", JOptionPane.YES_NO_OPTION);
//
//        if (resposta == JOptionPane.YES_OPTION) {
//            txt_NomeAdvogado.requestFocus();
//        }
    }//GEN-LAST:event_btn_atualizarActionPerformed

    private void btn_eliminarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_eliminarKeyPressed
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_LEFT:

                break;
            case KeyEvent.VK_RIGHT:
                btn_atualizar.requestFocus();
                break;

        }
    }//GEN-LAST:event_btn_eliminarKeyPressed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        remover();
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void cb_celasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cb_celasKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_celasKeyPressed

    private void cb_celasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_celasActionPerformed
        recluso.setCelas((Celas) cb_celas.getSelectedItem());
        Celas cela = (Celas) (cb_celas.getSelectedItem());

        if (Arrays.toString(cb_celas.getSelectedObjects()).equals("[A]")) {
            jLabel7.setText(" Estado da cela:      " + recluso.getCelas().getEstadoDaCela());
            lbl_nuemroDecamasEcapacidadeMaxima.setText(recluso.getCelas().getCapacitMax() + "");
            lbl_cama.setText(recluso.getCelas().getNrcama() + "");
            int verificar = Integer.parseInt(lbl_nuemroDecamasEcapacidadeMaxima.getText());
            if (verificar <= 2) {
                lbl_cama.setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.RED));
                lbl_nuemroDecamasEcapacidadeMaxima.setForeground(Color.RED);
            } else {
                lbl_cama.setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.GREEN));

            }

        } else if (Arrays.toString(cb_celas.getSelectedObjects()).equals("[B]")) {
            jLabel7.setText(" Estado da cela: " + recluso.getCelas().getEstadoDaCela());
            lbl_nuemroDecamasEcapacidadeMaxima.setText(recluso.getCelas().getCapacitMax() + "");
            lbl_cama.setText(recluso.getCelas().getNrcama() + "");
            int verificar = Integer.parseInt(lbl_nuemroDecamasEcapacidadeMaxima.getText());
            if (verificar <= 2) {
                lbl_cama.setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.RED));
                lbl_nuemroDecamasEcapacidadeMaxima.setForeground(Color.RED);
            } else {
                lbl_cama.setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.GREEN));

            }
        } else if (Arrays.toString(cb_celas.getSelectedObjects()).equals("[C]")) {
            jLabel7.setText(" Estado da cela: " + recluso.getCelas().getEstadoDaCela());
            lbl_nuemroDecamasEcapacidadeMaxima.setText(recluso.getCelas().getCapacitMax() + "");
            lbl_cama.setText(recluso.getCelas().getNrcama() + "");
            int verificar = Integer.parseInt(lbl_nuemroDecamasEcapacidadeMaxima.getText());
            if (verificar <= 2) {
                lbl_cama.setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.RED));
                lbl_nuemroDecamasEcapacidadeMaxima.setForeground(Color.RED);
            } else {
                lbl_cama.setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.GREEN));

            }
        } else if (Arrays.toString(cb_celas.getSelectedObjects()).equals("[D]")) {
            jLabel7.setText(" Estado da cela: " + recluso.getCelas().getEstadoDaCela());
            lbl_nuemroDecamasEcapacidadeMaxima.setText(recluso.getCelas().getCapacitMax() + "");
            lbl_cama.setText(recluso.getCelas().getNrcama() + "");
            int verificar = Integer.parseInt(lbl_nuemroDecamasEcapacidadeMaxima.getText());
            if (verificar <= 2) {
                lbl_cama.setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.RED));
                lbl_nuemroDecamasEcapacidadeMaxima.setForeground(Color.RED);
            } else {
                lbl_cama.setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.GREEN));

            }
        }
    }//GEN-LAST:event_cb_celasActionPerformed

    private void cb_crimesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cb_crimesKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_crimesKeyPressed

    private void cb_crimesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_crimesActionPerformed
        addTijList();

    }//GEN-LAST:event_cb_crimesActionPerformed

    private void tb_reclusoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tb_reclusoKeyPressed
        switch (evt.getKeyCode()) {

            case KeyEvent.VK_UP:

                break;

        }
    }//GEN-LAST:event_tb_reclusoKeyPressed

    private void txt_pesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_pesquisarKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_BACK_SPACE) {
            modelo.removeAllElements();

        }


    }//GEN-LAST:event_txt_pesquisarKeyReleased

    private void rb_MasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_MasculinoActionPerformed
        btn_foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Jail_ts2022/icons/PrisonerM.png")));

    }//GEN-LAST:event_rb_MasculinoActionPerformed

    private void rb_FemininoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_FemininoActionPerformed
        btn_foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Jail_ts2022/icons/PrisonerF.png")));

    }//GEN-LAST:event_rb_FemininoActionPerformed

    private void cb_nivelAcadademicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_nivelAcadademicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_nivelAcadademicoActionPerformed

    private void txt_nCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nCasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nCasaActionPerformed

    private void txt_nCasaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nCasaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nCasaKeyPressed

    private void txt_nCasaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nCasaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nCasaKeyTyped

    private void txt_quarteiraoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_quarteiraoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_quarteiraoActionPerformed

    private void txt_quarteiraoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_quarteiraoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_quarteiraoKeyPressed

    private void txt_quarteiraoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_quarteiraoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_quarteiraoKeyTyped

    private void txt_bairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_bairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_bairroActionPerformed

    private void txt_bairroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_bairroKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_bairroKeyPressed

    private void txt_bairroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_bairroKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_bairroKeyTyped

    private void cb_provinciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_provinciasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_provinciasActionPerformed

    private void txt_ruaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ruaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ruaKeyTyped

    private void txt_ruaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ruaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ruaKeyPressed

    private void txt_ruaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ruaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ruaActionPerformed

    private void txt_NomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_NomeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (Pattern.matches("^[a-zA-Z]+$", txt_Nome.getText())) {
                txt_Nome.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.GREEN));
                txt_Apelido.requestFocus();
                lbl_frequecia.setText(recluso.getFrequencia());
                lbl_idregistro.setText(String.valueOf(reclusaoDAo.reclusoId()));
                lbl_idregistro1.setText(String.valueOf(reclusaoDAo.reclusoId()));
                Setarcodigo();
                FormatDatachoos();
                naturaluadeCb();
                jlist_caracterizar.setEnabled(true);
                txt_Apelido.setEnabled(true);

            } else {

                txt_Nome.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.red));
                txt_Nome.requestFocus();

            }

        } else if (evt.getKeyCode() == KeyEvent.VK_BACK_SPACE) {
            txt_Nome.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.BLACK));
        }
    }//GEN-LAST:event_txt_NomeKeyPressed

    private void txt_ApelidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ApelidoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            if (Pattern.matches("^[a-zA-Z]+$", txt_Apelido.getText())) {
                txt_Apelido.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.GREEN));
                txt_NumeroDeBI.requestFocus();
                txt_NumeroDeBI.setEnabled(true);
            } else {

                txt_Apelido.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.red));
                txt_Apelido.requestFocus();
            }

        } else if (evt.getKeyCode() == KeyEvent.VK_BACK_SPACE) {

            txt_Apelido.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.BLACK));

        }
    }//GEN-LAST:event_txt_ApelidoKeyPressed

    private void txt_ApelidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ApelidoKeyTyped
        txt_Apelido.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.BLACK));
    }//GEN-LAST:event_txt_ApelidoKeyTyped

    private void cb_crimesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb_crimesMouseClicked

        cb_crimes.removeItem(cb_crimes.getSelectedItem());
    }//GEN-LAST:event_cb_crimesMouseClicked

    private void tb_reclusoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_reclusoMouseClicked

        cb_EstadoDePrisao.addItem("Foragido");
        lbl_penaDefinida.setVisible(true);
        sett_campos();
    }//GEN-LAST:event_tb_reclusoMouseClicked

    private void cb_crimesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_crimesItemStateChanged

    }//GEN-LAST:event_cb_crimesItemStateChanged

    private void btn_Limpar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Limpar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Limpar2ActionPerformed

    private void btn_Limpar2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_Limpar2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Limpar2KeyPressed
    void cb_provincias() {
        if (Arrays.toString(cb_naturalidade.getSelectedObjects()).equals("[Mocambicana]")) {
            cb_provincias.removeAllItems();
            for (int i = 0; i < listarProvincia.size(); i++) {

                cb_provincias.addItem(listarProvincia.get(i));

            }
        } else if (Arrays.toString(cb_naturalidade.getSelectedObjects()).equals("[Angolana]")) {
            cb_provincias.removeAllItems();
        } else if (Arrays.toString(cb_naturalidade.getSelectedObjects()).equals("[Cabo Verdiana]")) {
            cb_provincias.removeAllItems();
        } else if (Arrays.toString(cb_naturalidade.getSelectedObjects()).equals("[Sul Africana]")) {
            cb_provincias.removeAllItems();
        } else if (Arrays.toString(cb_naturalidade.getSelectedObjects()).equals("[Tanzaniana]")) {
            cb_provincias.removeAllItems();
        }
    }
    private void txt_NumeroDeBIKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_NumeroDeBIKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            rb_Masculino.setEnabled(true);
            rb_Feminino.setEnabled(true);
            FrequeciasDeprisao();
            reclusoExistente();
        }


    }//GEN-LAST:event_txt_NumeroDeBIKeyPressed

    private void jList_crimesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList_crimesMouseClicked
        removeTojlist();
        if (modelListCrimes.isEmpty()) {
            lbl_penaDefinida.setText(String.valueOf(localDate));
        }
    }//GEN-LAST:event_jList_crimesMouseClicked

    private void txt_pesquisarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_pesquisarKeyPressed
        if (enter == 0) {
            listarPesquisa();
        } else {
            enter = 0;
        }

    }//GEN-LAST:event_txt_pesquisarKeyPressed

    private void txt_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pesquisarActionPerformed
        jList1.setVisible(false);
        enter = 1;
    }//GEN-LAST:event_txt_pesquisarActionPerformed

    private void jList1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jList1KeyReleased
        mostrarPesqisa();
        jList1.setVisible(false);
    }//GEN-LAST:event_jList1KeyReleased

    private void cb_crimesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb_crimesMousePressed

    }//GEN-LAST:event_cb_crimesMousePressed

    private void cb_crimesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb_crimesMouseReleased

    }//GEN-LAST:event_cb_crimesMouseReleased

    private void btn_salvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvar1ActionPerformed
        table1Registrar();
    }//GEN-LAST:event_btn_salvar1ActionPerformed

    private void cb_crimesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb_crimesMouseEntered

    }//GEN-LAST:event_cb_crimesMouseEntered

    private void lbl_penaDefinidaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_penaDefinidaMouseEntered

    }//GEN-LAST:event_lbl_penaDefinidaMouseEntered

    private void cb_EstadoDePrisaoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_EstadoDePrisaoItemStateChanged
        if (Arrays.toString(cb_EstadoDePrisao.getSelectedObjects()).equals("[condenado]")) {
            cb_crimes.removeAllItems();
            modelListCrimes.clear();
            lbl_penaDefinida.setText(String.valueOf(localDate));
            for (int i = 0; i < listaCrimes.size(); i++) {
                if (!listaCrimes.get(i).getCategoriaDeCrime().equalsIgnoreCase("Nao definido")) {
                    cb_crimes.addItem(listaCrimes.get(i));

                }

            }

        } else if (Arrays.toString(cb_EstadoDePrisao.getSelectedObjects()).equals("[espera de julgamento]")) {
            cb_crimes.removeAllItems();
            modelListCrimes.clear();
            lbl_penaDefinida.setText(String.valueOf(localDate));
            for (int i = 0; i < listaCrimes.size(); i++) {
                if (listaCrimes.get(i).getCategoriaDeCrime().equalsIgnoreCase("Nao definido")) {
                    cb_crimes.addItem(listaCrimes.get(i));

                }

            }

        }
    }//GEN-LAST:event_cb_EstadoDePrisaoItemStateChanged

    private void cb_naturalidadeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_naturalidadeItemStateChanged
        cb_provincias();
    }//GEN-LAST:event_cb_naturalidadeItemStateChanged
    void removeTojlist() {

        try {
            cb_crimes.addItem(jList_crimes.getSelectedValue());
            Crimes removido = (Crimes) jList_crimes.getSelectedValue();
            localDate = localDate.minusMonths(Long.parseLong(removido.getDuracaoEmMeses()));
            localDate = localDate.minusYears(Long.parseLong(removido.getDuracaoEmAno()));
            lbl_penaDefinida.setText(localDate + "");
            modelListCrimes.removeElement(jList_crimes.getSelectedValue());
            lbl_duracaoEmMeses.setText(removido.getDuracaoEmMeses());
            lbl_duracaoEmAno.setText(removido.getDuracaoEmAno());
            lbl_duracaoEmMeses.setText(null);
            lbl_duracaoEmAno.setText(null);
            JOptionPane.showMessageDialog(null, "O crime " + removido.getCategoriaDeCrime() + " foi retirado da lista", "", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Selecione um crime para retirar da lista", "", JOptionPane.WARNING_MESSAGE);
        }

    }

    void addTijList() {
        try {
            modelListCrimes.addElement(cb_crimes.getSelectedItem());
            Crimes selecionado = (Crimes) cb_crimes.getSelectedItem();
            localDate = localDate.plusMonths(Long.parseLong(selecionado.getDuracaoEmMeses()));
            localDate = localDate.plusYears(Long.parseLong(selecionado.getDuracaoEmAno()));
            //
            lbl_duracaoEmMeses.setText(null);
            lbl_duracaoEmAno.setText(null);
            //
            lbl_duracaoEmMeses.setText(selecionado.getDuracaoEmMeses());
            lbl_duracaoEmAno.setText(selecionado.getDuracaoEmAno());
            lbl_penaDefinida.setText(localDate + "");
            //
            int totalAnos = 0;
            int controlAnos = Integer.parseInt(selecionado.getDuracaoEmAno());
            totalAnos = totalAnos + controlAnos;
            if (totalAnos >= 30) {
                cb_crimes.setEnabled(true);
                JOptionPane.showMessageDialog(null, "O recluso nao pone receber uma pena superior a 30 anos ", "", JOptionPane.INFORMATION_MESSAGE);
            }
            System.out.println(" aos de prisao " + totalAnos);;
            // JOptionPane.showMessageDialog(null, "Crime addcionado a lista de crimes", "", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
        }
    }

    /* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ declaracao de variaveis ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
    Connection conexao = null;
    PreparedStatement stat = null; //pst quer dizer  PreparedStatement
    ResultSet rst = null;
    //
    LocalDate plusMonths;
    LocalDate localDate = LocalDate.now();
    //

    // ReclusoDao rd = new ReclusoDao();
    CelasDao celaDAo = new CelasDao();
    List<Celas> listarCelas = celaDAo.ListarCelas();
    //----
    CrimesDAo crimes = new CrimesDAo();
    List<Crimes> listaCrimes = crimes.ListaCrimes();
    //---- CAMAS 
//    //
    ProvinciasDAo provincia = new ProvinciasDAo();
    List<Provincias> listarProvincia = provincia.ListaProvincias();
    //
    NacionalidadeDao nacionalidade = new NacionalidadeDao();
    List<Nacionalidade> listarNacionalidade = nacionalidade.ListaNacionalidade();
    //

    DefaultListModel modelListCrimes = new DefaultListModel();

    // classe model
    Recluso recluso = new Recluso();
    Provincias provincias = new Provincias();
    Endereco endereco = new Endereco();
    Crimes crime = new Crimes();
    Celas cela = new Celas();

    // classe dao
    ReclusoDao reclusaoDAo = new ReclusoDao();
    EnderecoDAo enderecoDAo = new EnderecoDAo();
    CrimesDAo crimesDAo = new CrimesDAo();
    DefaultListModel modelo = new DefaultListModel();
    //
    int enter = 0;
    String[] index = new String[5];
    String crimesCometidos = null;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser JDataFormatada;
    private javax.swing.JButton btn_Limpar2;
    private javax.swing.JButton btn_atualizar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_foto;
    private javax.swing.JButton btn_proximo;
    private javax.swing.JButton btn_salvar1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox<Object> cb_EstadoDePrisao;
    private javax.swing.JComboBox<Celas> cb_celas;
    private javax.swing.JComboBox<Crimes> cb_crimes;
    private javax.swing.JComboBox<Object> cb_doencas;
    private javax.swing.JComboBox<Object> cb_naturalidade;
    private javax.swing.JComboBox<Object> cb_nivelAcadademico;
    private javax.swing.JComboBox<Jail_ts2022.model.Provincias> cb_provincias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<Crimes> jList_crimes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTextArea jlist_caracterizar;
    private javax.swing.JLabel lbl_Codigo;
    private javax.swing.JLabel lbl_cama;
    private javax.swing.JLabel lbl_duracaoEmAno;
    private javax.swing.JLabel lbl_duracaoEmMeses;
    private javax.swing.JLabel lbl_frequecia;
    private javax.swing.JLabel lbl_idFuncionaio;
    private javax.swing.JLabel lbl_idregistro;
    private javax.swing.JLabel lbl_idregistro1;
    private javax.swing.JLabel lbl_nuemroDecamasEcapacidadeMaxima;
    private javax.swing.JLabel lbl_penaDefinida;
    private javax.swing.JRadioButton rb_Feminino;
    private javax.swing.JRadioButton rb_Masculino;
    private javax.swing.JTable tb_recluso;
    private javax.swing.JTextArea txtA_bens;
    private javax.swing.JTextField txt_Apelido;
    private javax.swing.JTextField txt_Nome;
    private javax.swing.JFormattedTextField txt_NumeroDeBI;
    private javax.swing.JTextField txt_bairro;
    private javax.swing.JTextField txt_nCasa;
    private javax.swing.JTextField txt_pesquisar;
    private javax.swing.JTextField txt_quarteirao;
    private javax.swing.JTextField txt_rua;
    // End of variables declaration//GEN-END:variables

    public void table1Registrar() {
        try {

            int contt = 0;
            for (int i = 0; i < tb_recluso.getRowCount(); i++) {
                if (txt_Nome.getText().equals(tb_recluso.getModel().getValueAt(i, 1)) && txt_Nome.getText().equals(tb_recluso.getModel().getValueAt(i, 2))) {
                    contt = 1;
                }
            }

            if (contt >= 1) {
                int i = 0;
                i = JOptionPane.showConfirmDialog(null, "Este Recluso esteve preso. Dseja recuperar os dados??", "Notificação ", JOptionPane.YES_NO_OPTION);
                if (i == JOptionPane.YES_OPTION) {
                    System.out.println(" Preencher os dados ");
                }
            } else {

                recluso.setId_registro(lbl_idregistro.getText());
                recluso.setCodigo(lbl_Codigo.getText());
                recluso.setApelido(txt_Apelido.getText());
                recluso.setNome(txt_Nome.getText());
                recluso.setNumeroDeBI(txt_NumeroDeBI.getText());

                SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
                String anoStr = formato.format(JDataFormatada.getDate());
                recluso.setDatadeNascimento(anoStr);

                if (rb_Masculino.isSelected()) {
                    recluso.setGenero(rb_Masculino.getActionCommand());
                } else if (rb_Feminino.isSelected()) {
                    recluso.setGenero(rb_Feminino.getActionCommand());
                }
                recluso.setRegistroDeBens(txtA_bens.getText());
                recluso.setNivelAcademico(cb_nivelAcadademico.getSelectedItem().toString());

                recluso.setDoenca(cb_doencas.getSelectedItem().toString());
                recluso.setEstadoDaPrisao(cb_EstadoDePrisao.getSelectedItem().toString());
                // salvar
                ArrayList<Crimes> lista = new ArrayList<>();
                for (int i = 0; i < modelListCrimes.size(); i++) {
                    lista.add((Crimes) modelListCrimes.get(i));
                }
                recluso.setCrime(lista);
                // crime.setCategoriaDeCrime(String.valueOf(crime));
                recluso.setDuracaoDapena(String.valueOf(lbl_penaDefinida.getText()));
                reclusaoDAo.saveRecluso(recluso);
                /*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ registrar endreco ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
                celaDAo.ocuparAcela(recluso);
                crimesDAo.tbrecluso_has_tbcrimes(recluso);
                // endreco
                endereco.setBairro(txt_bairro.getText());
                recluso.setEndereco(endereco);
                endereco.setRua(txt_rua.getText());
                recluso.setEndereco(endereco);
                endereco.setCasa(txt_nCasa.getText());
                recluso.setEndereco(endereco);
                endereco.setQuarteirao(txt_quarteirao.getText());
                recluso.setEndereco(endereco);
                recluso.setId_registro(lbl_idregistro.getText());
                //provincia;
                endereco.setProvincias((Provincias) cb_provincias.getSelectedItem());
                recluso.setEndereco(endereco);
                // endereco salvar 
                enderecoDAo.regitrarEndereco(recluso);
                int i = JOptionPane.showConfirmDialog(null, " vai registar advogado?", "", JOptionPane.YES_NO_OPTION);

                if (i == JOptionPane.YES_OPTION) {
                    new TelaAdvogado().setVisible(true);
                }
                LimparCampos();
                PrencherTabela();

            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e + " Erro problema na digitação dos dados ", "Notificação", JOptionPane.ERROR_MESSAGE);
            System.out.println(e);
        }

    }

//    void table2Registrar() {
//        /*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ registrar crimes ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
//
////        if (Arrays.toString(cb_Estado.getSelectedObjects()).equals("[condenado]")) {
////
////        } else if (Arrays.toString(cb_Estado.getSelectedObjects()).equals("[espera de julgamento]")) {
////            for (int i = 0; i < modelListCrimes.size(); i++) {
////
////                crime = (Crimes) modelListCrimes.getElementAt(i);
////
////                System.out.println(" Crimes selecionado: " + crime.getCategoriaDeCrime());
////            }
////            crime.setCategoriaDeCrime(String.valueOf(crime));
////            recluso.setDuracaoDapena(String.valueOf(lbl_penaDefinida.getText()));
////        }
//    }

    /* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Atualizar dados de funcionario ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
    public void Atualizar() {

        try {

            /*validando os campos de preechimento
             */
            if (txt_Nome.getText().isEmpty() || txt_Apelido.getText().isEmpty()
                    || txt_NumeroDeBI.getText().isEmpty() || cb_provincias.getActionCommand().isEmpty()
                    || cb_crimes.getActionCommand().isEmpty() || cb_EstadoDePrisao.getActionCommand().isEmpty()
                    || cb_celas.getActionCommand().isEmpty()) {

                JOptionPane.showMessageDialog(null, "Preencha todos campos obrigatorios", "Atenção", JOptionPane.WARNING_MESSAGE);

            } else {

                Recluso add = new Recluso();

                add.setApelido(txt_Apelido.getText());
                add.setCodigo(lbl_Codigo.getText());
                add.setNome(txt_Nome.getText());
//                    add.setEndereco(txt_ndereco.getText());
                add.setNumeroDeBI(txt_NumeroDeBI.getText());
                add.setNuit(txt_NumeroDeBI.getText());
//                    add.setRegistroDeBens(tA_registroDeBens.getText());
                //
                SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
                String anoStr = formato.format(JDataFormatada.getDate());
                add.setDatadeNascimento(anoStr);

                //
//                    add.setContacto(tf_contacto.getText());
                if (rb_Masculino.isSelected()) {
                    add.setGenero(rb_Masculino.getActionCommand());
                } else if (rb_Feminino.isSelected()) {
                    add.setGenero(rb_Feminino.getActionCommand());
                }
//                    //setNomeDeAdvogado(txt_NomeAdvogado.getText());
//                    add.setContactoDeAdvogado(tf_contactoAdvogado.getText());
//                    add.setEmail(txt_email.getText());
////                    add.setRegistroDeBens(tA_registroDeBens.getText());
////                    add.setEndereco(jTextField.getText());
//
//                    add.setNivelAcademico(cb_nivelAcademico.getSelectedItem().toString());
//                    add.setNaturalidade(cb_nacionalidade.getSelectedItem().toString());
//                    add.setDoenca(cb_EstadoCivil.getSelectedItem().toString());
//                    add.setEstadosDecriminosos(cb_Estado.getSelectedItem().toString());
//                    add.setCelas((Celas) cb_celas.getSelectedItem());
////                    add.setDuracaoDapena(cb_penaEmAno.getSelectedItem().toString() + cb_penaEmMeses.getSelectedItem().toString());

                ReclusoDao saveDao = new ReclusoDao();
                // saveDao.save(add,);
                LimparCampos();
                jTabbedPane.setSelectedIndex(1);

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e + " Erro problema na digitação dos dados ", "Notificação", JOptionPane.ERROR_MESSAGE);
            System.out.println(e);
        }

    }

    /* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Remover dados de funcionario ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
    public void remover() {

        try {

            /*validando os campos de preechimento
             */
            if (txt_Nome.getText().isEmpty() || txt_Apelido.getText().isEmpty()
                    || txt_NumeroDeBI.getText().isEmpty() || cb_provincias.getActionCommand().isEmpty()
                    || cb_crimes.getActionCommand().isEmpty() || cb_EstadoDePrisao.getActionCommand().isEmpty()
                    || cb_celas.getActionCommand().isEmpty()) {

                JOptionPane.showMessageDialog(null, "Preencha todos campos obrigatorios", "Atenção", JOptionPane.WARNING_MESSAGE);

            } else {

                recluso.setApelido(txt_Apelido.getText());
                recluso.setCodigo(lbl_Codigo.getText());
                recluso.setNome(txt_Nome.getText());
                reclusaoDAo.removeRecluso(recluso);

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e + " Erro problema na digitação dos dados ", "Notificação", JOptionPane.ERROR_MESSAGE);
            System.out.println(e);
        }

    }
//----------------------------------------------------------------------------------------------------------

}
