/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Jail_ts2022.views;

import Jail_ts2022.model.Funcionario;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.Timer;

/**
 *
 * @author Klesia
 */
public final class relatorioImpresso extends javax.swing.JInternalFrame {

    public Funcionario usuarioActual;

    public Funcionario getUsuarioActual() {
        return usuarioActual;
    }

    public JLabel getLbl_nomeDorequerente() {
        return lbl_nomeDorequerente;
    }

   
    
    /**
     * Creates new form relatorioImpresso
     *
     */
    public relatorioImpresso() {
       this.usuarioActual = usuarioActual;
        initComponents();
        horaData();
        



    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    /* 

    public void GerarRelatorio() {
        new RelatorioPdf().gerarRelatorio(txtTotalDividas.getText(), txtMediaDividas.getText(), txtTotalPagas.getText(),lblTotalNPagas.getText(),
                txtDevMenorDivida.getText(), ttt.getText(), txtMenorDivida.getText(), txtMaiorDivida.getText());
        JOptionPane.showMessageDialog(rootPane, "Relatório gerado com sucesso \nna pasta do projecto!");

    }*/
    void horaData() {
        Date data = new Date();
        sdf = new SimpleDateFormat("dd MMMM yyyy");
        Calendar now = Calendar.getInstance();

        class hora implements ActionListener {

            @Override
            public void actionPerformed(ActionEvent e) {
                Calendar now = Calendar.getInstance();
                lbl_horaData.setText(String.format(" %1$tH : %1$tM : %1$tS", now));

            }

        }

        Timer timer = new Timer(1000, new hora());
        timer.start();

        lbl_data.setText("Data: " + sdf.format(data));

    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbl_horaData = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lbl_data = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lbl_nomeDorequerente = new javax.swing.JLabel();

        jPanel1.setLayout(null);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Jail_ts2022/icons/printer_green_10875 - Copy.png"))); // NOI18N
        jButton1.setText("Imprimir");
        jPanel1.add(jButton1);
        jButton1.setBounds(780, 540, 210, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 360, 1030, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 150, 1030, 20);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("imprimir Relatorio ");
        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        jPanel1.add(jLabel4);
        jLabel4.setBounds(270, 40, 460, 80);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Feminino: ");
        jLabel6.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        jPanel1.add(jLabel6);
        jLabel6.setBounds(340, 180, 180, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Total: ");
        jLabel7.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        jPanel1.add(jLabel7);
        jLabel7.setBounds(810, 180, 180, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Masculino: ");
        jLabel8.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 180, 180, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Activos: ");
        jLabel9.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        jPanel1.add(jLabel9);
        jLabel9.setBounds(270, 390, 180, 30);

        lbl_horaData.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lbl_horaData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_horaData.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(lbl_horaData);
        lbl_horaData.setBounds(200, 570, 90, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Total: ");
        jLabel11.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        jPanel1.add(jLabel11);
        jLabel11.setBounds(790, 440, 180, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("***************************************************************************************************************");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 490, 1030, 20);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("frequencia maior que 1 :");
        jLabel12.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        jPanel1.add(jLabel12);
        jLabel12.setBounds(30, 390, 200, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("criminosos com problemas de saude: ");
        jLabel13.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        jPanel1.add(jLabel13);
        jLabel13.setBounds(280, 310, 280, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("crime com maior frequencia: ");
        jLabel14.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        jPanel1.add(jLabel14);
        jLabel14.setBounds(20, 310, 230, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("nivel de academico medio : ");
        jLabel15.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        jPanel1.add(jLabel15);
        jLabel15.setBounds(280, 250, 280, 30);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel16.setText("Requerente: ");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(20, 510, 100, 20);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("foragidos: ");
        jLabel17.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        jPanel1.add(jLabel17);
        jLabel17.setBounds(270, 450, 180, 30);

        lbl_data.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lbl_data.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_data.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(lbl_data);
        lbl_data.setBounds(20, 570, 180, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 220, 1030, 20);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("nivel de academico superior : ");
        jLabel18.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        jPanel1.add(jLabel18);
        jLabel18.setBounds(600, 250, 260, 30);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel19.setText("nivel de academico basico : ");
        jLabel19.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        jPanel1.add(jLabel19);
        jLabel19.setBounds(20, 250, 230, 30);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Jail_ts2022/icons/criminal-in-jail-silhouette.png"))); // NOI18N
        jPanel1.add(jLabel10);
        jLabel10.setBounds(830, 10, 120, 130);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Jail_ts2022/icons/criminal-running-with-stolen-woman-bag.png"))); // NOI18N
        jPanel1.add(jLabel20);
        jLabel20.setBounds(50, 10, 140, 120);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Soltos: ");
        jLabel21.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        jPanel1.add(jLabel21);
        jLabel21.setBounds(30, 450, 200, 30);

        lbl_nomeDorequerente.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jPanel1.add(lbl_nomeDorequerente);
        lbl_nomeDorequerente.setBounds(20, 530, 370, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1056, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
        );

        setBounds(0, 0, 1072, 638);
    }// </editor-fold>//GEN-END:initComponents

    private SimpleDateFormat sdf;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_data;
    private javax.swing.JLabel lbl_horaData;
    public javax.swing.JLabel lbl_nomeDorequerente;
    // End of variables declaration//GEN-END:variables
}
