/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Jail_ts2022.views;

import Jail_ts2022.controller.ControllerFuncionario;
import Jail_ts2022.dao.AdvogadoDao;
import Jail_ts2022.dao.ReclusoDao;
import Jail_ts2022.model.Advogado;
import Jail_ts2022.model.Recluso;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Klesia
 */
public class TelaAdvogado extends javax.swing.JFrame {

    Connection conexao = null;
    PreparedStatement stat = null; //pst quer dizer  PreparedStatement
    ResultSet rst = null;
    AdvogadoDao advogadoDAo = new AdvogadoDao();
    
    

    /**
     * Creates new form teste
     */
    public TelaAdvogado() {
        initComponents();

    }

    ReclusoDao g = new ReclusoDao();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        lbl_idAdvogado = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnLimpar = new javax.swing.JButton();
        txt_NomeAdvogado = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_eliminar1 = new javax.swing.JButton();
        btn_atualizar1 = new javax.swing.JButton();
        btn_salvar = new javax.swing.JButton();
        jC_registrar = new javax.swing.JCheckBox();
        jC_selecionar = new javax.swing.JCheckBox();
        cb_ListarAdvogados = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        tf_contactoAdvogado = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(null);

        jLabel40.setBackground(new java.awt.Color(255, 255, 255));
        jLabel40.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(51, 51, 51));
        jLabel40.setText("Id Advogado");
        jPanel1.add(jLabel40);
        jLabel40.setBounds(20, 20, 70, 20);

        lbl_idAdvogado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_idAdvogado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_idAdvogado.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        jPanel1.add(lbl_idAdvogado);
        lbl_idAdvogado.setBounds(100, 20, 50, 25);

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Nome do Advogado:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(30, 80, 150, 16);

        btnLimpar.setBackground(new java.awt.Color(204, 255, 255));
        btnLimpar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Jail_ts2022/icons/Cancel.png"))); // NOI18N
        btnLimpar.setText("Cancelar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpar);
        btnLimpar.setBounds(300, 290, 150, 30);

        txt_NomeAdvogado.setBackground(new java.awt.Color(240, 240, 240));
        txt_NomeAdvogado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_NomeAdvogado.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        txt_NomeAdvogado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_NomeAdvogadoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_NomeAdvogadoKeyTyped(evt);
            }
        });
        jPanel1.add(txt_NomeAdvogado);
        txt_NomeAdvogado.setBounds(30, 100, 240, 30);

        txt_email.setBackground(new java.awt.Color(240, 240, 240));
        txt_email.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_email.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });
        txt_email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_emailKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_emailKeyTyped(evt);
            }
        });
        jPanel1.add(txt_email);
        txt_email.setBounds(30, 170, 420, 30);

        jLabel32.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray), "Dados de Advogado:", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.ABOVE_BOTTOM, new java.awt.Font("Segoe UI", 3, 11))); // NOI18N
        jPanel1.add(jLabel32);
        jLabel32.setBounds(20, 50, 480, 180);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Email a contactar:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 140, 120, 20);

        btn_eliminar1.setBackground(new java.awt.Color(204, 255, 255));
        btn_eliminar1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_eliminar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Jail_ts2022/icons/remov.png"))); // NOI18N
        btn_eliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminar1ActionPerformed(evt);
            }
        });
        btn_eliminar1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_eliminar1KeyPressed(evt);
            }
        });
        jPanel1.add(btn_eliminar1);
        btn_eliminar1.setBounds(250, 240, 70, 25);

        btn_atualizar1.setBackground(new java.awt.Color(204, 255, 255));
        btn_atualizar1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_atualizar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Jail_ts2022/icons/atualizar.png"))); // NOI18N
        btn_atualizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atualizar1ActionPerformed(evt);
            }
        });
        btn_atualizar1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_atualizar1KeyPressed(evt);
            }
        });
        jPanel1.add(btn_atualizar1);
        btn_atualizar1.setBounds(350, 240, 60, 25);

        btn_salvar.setBackground(new java.awt.Color(204, 255, 255));
        btn_salvar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Jail_ts2022/icons/add.png"))); // NOI18N
        btn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarActionPerformed(evt);
            }
        });
        btn_salvar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_salvarKeyPressed(evt);
            }
        });
        jPanel1.add(btn_salvar);
        btn_salvar.setBounds(440, 240, 60, 25);

        jC_registrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jC_registrar.setText("Regitar Advogado");
        jC_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jC_registrarActionPerformed(evt);
            }
        });
        jPanel1.add(jC_registrar);
        jC_registrar.setBounds(240, 20, 150, 23);

        jC_selecionar.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jC_selecionar.setText(" escolher Advogados  um");
        jC_selecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jC_selecionarActionPerformed(evt);
            }
        });
        jPanel1.add(jC_selecionar);
        jC_selecionar.setBounds(20, 240, 170, 23);

        cb_ListarAdvogados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_ListarAdvogadosActionPerformed(evt);
            }
        });
        jPanel1.add(cb_ListarAdvogados);
        cb_ListarAdvogados.setBounds(20, 280, 160, 30);

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 51, 51));
        jLabel25.setText("Contacto Advogado:");
        jPanel1.add(jLabel25);
        jLabel25.setBounds(300, 70, 130, 20);

        tf_contactoAdvogado.setBackground(new java.awt.Color(240, 240, 240));
        tf_contactoAdvogado.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        try {
            tf_contactoAdvogado.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(+258)  #########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tf_contactoAdvogado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tf_contactoAdvogado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_contactoAdvogadoKeyPressed(evt);
            }
        });
        jPanel1.add(tf_contactoAdvogado);
        tf_contactoAdvogado.setBounds(300, 100, 150, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 560, 340);

        setSize(new java.awt.Dimension(579, 362));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_NomeAdvogadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_NomeAdvogadoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NomeAdvogadoKeyPressed

    private void txt_NomeAdvogadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_NomeAdvogadoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NomeAdvogadoKeyTyped

    private void txt_emailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_emailKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (f.validarEmail(txt_email.getText()) == false) {
                JOptionPane.showMessageDialog(null, "Email Digitado Inválido! Por Favor Introduza um email válido", "Atenção", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_txt_emailKeyPressed

    private void txt_emailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_emailKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailKeyTyped

    private void btn_eliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_eliminar1ActionPerformed

    private void btn_eliminar1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_eliminar1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_eliminar1KeyPressed

    private void btn_atualizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atualizar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_atualizar1ActionPerformed

    private void btn_atualizar1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_atualizar1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_atualizar1KeyPressed

    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarActionPerformed

    }//GEN-LAST:event_btn_salvarActionPerformed

    private void btn_salvarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_salvarKeyPressed
        if (f.validarEmail(txt_email.getText()) == false) {
            JOptionPane.showMessageDialog(null, "Email Digitado Inválido! Por Favor Introduza um email válido", "Atenção", JOptionPane.WARNING_MESSAGE);
            btn_salvar.setEnabled(false);
        } else if (tf_contactoAdvogado.getText().length() < 16) {
            btn_salvar.setEnabled(false);
            JOptionPane.showMessageDialog(null, "Os Campos Contactos Devem Ser Preenchidos \n O número de Telefone Deve conter apenas 9 digito!!", "Atenção", JOptionPane.WARNING_MESSAGE);
        } else if (txt_NomeAdvogado.getText().isEmpty()) {
            btn_salvar.setEnabled(false);
            JOptionPane.showMessageDialog(null, "O Campo Nome do Advogado deve Preenchido!", "Atenção", JOptionPane.WARNING_MESSAGE);
        } else if (tf_contactoAdvogado.getText().isEmpty()) {
            btn_salvar.setEnabled(false);
            JOptionPane.showMessageDialog(null, "O Campo Telefone de Advogado Deve Ser Preenchido!", "Atenção", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btn_salvarKeyPressed

    private void jC_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jC_registrarActionPerformed
        if (jC_registrar.isSelected()) {
            txt_NomeAdvogado.setEnabled(true);
            cb_ListarAdvogados.setEnabled(true);
            txt_email.setEnabled(true);
//            tf_contactoAdvogado.setEnabled(true);
            cb_ListarAdvogados.setVisible(true);
        }
    }//GEN-LAST:event_jC_registrarActionPerformed

    private void jC_selecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jC_selecionarActionPerformed
        if (jC_selecionar.isSelected()) {
            cb_ListarAdvogados.setEnabled(false);
            listarAdvogado();
            txt_NomeAdvogado.setEnabled(false);
            txt_email.setEnabled(false);
            tf_contactoAdvogado.setEnabled(false);
        }


    }//GEN-LAST:event_jC_selecionarActionPerformed

    private void cb_ListarAdvogadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_ListarAdvogadosActionPerformed
        lbl_idAdvogado.setText(recluso.getAdvogado().getId_Advogado());
    }//GEN-LAST:event_cb_ListarAdvogadosActionPerformed

    private void tf_contactoAdvogadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_contactoAdvogadoKeyPressed

    }//GEN-LAST:event_tf_contactoAdvogadoKeyPressed

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed

    }//GEN-LAST:event_txt_emailActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        this.dispose();
       
    }//GEN-LAST:event_btnLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAdvogado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAdvogado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAdvogado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAdvogado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAdvogado().setVisible(true);
            }
        });
    }
    ControllerFuncionario f = new ControllerFuncionario();
    AdvogadoDao advogados = new AdvogadoDao();
    Advogado advogado = new Advogado();
    List<Advogado> listarAdvogados = advogados.listarAdvogado();
    ReclusoDao reclusaoDAo = new ReclusoDao();
    Recluso recluso = new Recluso();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btn_atualizar1;
    private javax.swing.JButton btn_eliminar1;
    private javax.swing.JButton btn_salvar;
    private javax.swing.JComboBox<Jail_ts2022.model.Advogado> cb_ListarAdvogados;
    private javax.swing.JCheckBox jC_registrar;
    private javax.swing.JCheckBox jC_selecionar;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_idAdvogado;
    private javax.swing.JFormattedTextField tf_contactoAdvogado;
    private javax.swing.JTextField txt_NomeAdvogado;
    private javax.swing.JTextField txt_email;
    // End of variables declaration//GEN-END:variables
 void listarAdvogado() {

        for (int i = 0; i < listarAdvogados.size(); i++) {
            cb_ListarAdvogados.addItem(listarAdvogados.get(i));

        }

    }

    void registrarAdvogado() {
        if (jC_selecionar.isSelected()) {

            recluso.setAdvogado((Advogado) cb_ListarAdvogados.getSelectedItem());
            advogadoDAo.tbrecluso_has_tbadvogados(recluso);

        } else if (jC_registrar.isSelected()) {
            advogado.setId_Advogado(lbl_idAdvogado.getText());
            recluso.setAdvogado(advogado);
            //
            advogado.setNomeDeAdvogado(txt_NomeAdvogado.getText());
            recluso.setAdvogado(advogado);
            //
            advogado.setEmailAdvogado(txt_email.getText());
            recluso.setAdvogado(advogado);
            //
            advogado.setContactoDeAdvogado(tf_contactoAdvogado.getText());
            recluso.setAdvogado(advogado);
            // salvar advogado
            advogadoDAo.regitrarAdvogado(recluso);
            advogadoDAo.tbrecluso_has_tbadvogados(recluso);
        }

    }

}
