/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Jail_ts2022.views;

import java.awt.event.KeyEvent;
import Jail_ts2022.model.Funcionario;
import com.toedter.calendar.JDateChooser;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author Mutisse
 */
public final class TelaPerfil extends javax.swing.JInternalFrame {

    private Funcionario usuarioActual = new Funcionario();

    public void setUsuarioActual(Funcionario usuarioActual) {
        this.usuarioActual = usuarioActual;
    }

    public JTextField getTxt_Nome() {
        return txt_Nome;
    }

    public JTextField getTxt_Apelido() {
        return txt_Apelido;
    }

    public JFormattedTextField getTf_nuit() {
        return tf_nuit;
    }

    public JTextField getTxt_email() {
        return txt_email;
    }

   
    public JRadioButton getRb_Femenino() {
        return rb_Femenino;
    }

    public JRadioButton getRb_Masculino() {
        return rb_Masculino;
    }

    public JLabel getLbl_perfil() {
        return lbl_Perfil;
    }

    public JDateChooser getCh_dataNascimento() {
        return Ch_dataNascimento;
    }

    public JLabel getLbl_Codigo() {
        return lbl_Codigo;
    }

    /**
     * Creates new form NewJInternalFrame
     *
     * @param f
     */
    public TelaPerfil() {

        initComponents();
        setar_campos();
        if (lbl_Perfil.getText().equalsIgnoreCase("Gestor")) {

        } else {
            jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Jail_ts2022/icons/human-icon-png-1903 (3).png")));

        }
    }

    void habilitar() {
        txt_Nome.setEnabled(true);
        txt_Apelido.setEnabled(true);
        txt_nbi.setEnabled(true);
        tf_nuit.setEnabled(true);
        Ch_dataNascimento.setEnabled(true);
        tf_contacto.setEnabled(true);

    }

    public void setar_campos() {
        /*  for (Usuarios user : UsuarioController.lista()) {
            txtNome.setText(user.getNome());
            txtUser.setText(user.getUsuario());
            if (user.getGenero().equals("Masculino")) {
                rb_Masculino.setSelected(true);
            } else if (user.getGenero().equals("Feminino")) {
                rb_Femenino.setSelected(true);
            }
            pfSenha.setText(user.getSenha());
            pfSenha1.setText(user.getSenha());
        }
         */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jCsenha = new javax.swing.JCheckBox();
        pfSenha = new javax.swing.JPasswordField();
        pfSenha1 = new javax.swing.JPasswordField();
        btn_Limpar = new javax.swing.JButton();
        btn_atualizar = new javax.swing.JButton();
        btn_salvar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txt_Nome = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_Apelido = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_nbi = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        tf_contacto = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        tf_nuit = new javax.swing.JFormattedTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rb_Masculino = new javax.swing.JRadioButton();
        rb_Femenino = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        Ch_dataNascimento = new com.toedter.calendar.JDateChooser();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cb_nacionnalidade = new javax.swing.JComboBox<>();
        lbl_Codigo = new javax.swing.JLabel();
        pfSenha2 = new javax.swing.JPasswordField();
        jLabel21 = new javax.swing.JLabel();
        lbl_Perfil = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        cb_naturalidade = new javax.swing.JComboBox<>();
        jLabel31 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Meu Perfil");
        setEnabled(false);
        setMinimumSize(new java.awt.Dimension(897, 606));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setMinimumSize(new java.awt.Dimension(897, 606));
        jPanel3.setPreferredSize(new java.awt.Dimension(897, 606));
        jPanel3.setLayout(null);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 10)); // NOI18N
        jLabel5.setText("Nova Senha:");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(200, 530, 110, 20);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 10)); // NOI18N
        jLabel6.setText("Confirmar senha:");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(330, 530, 112, 20);

        jCsenha.setBackground(new java.awt.Color(204, 204, 204));
        jCsenha.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jCsenha.setText("Mostrar a Senha ");
        jCsenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCsenhaActionPerformed(evt);
            }
        });
        jPanel3.add(jCsenha);
        jCsenha.setBounds(50, 510, 130, 20);

        pfSenha.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        pfSenha.setEnabled(false);
        pfSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pfSenhaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pfSenhaKeyReleased(evt);
            }
        });
        jPanel3.add(pfSenha);
        pfSenha.setBounds(200, 560, 110, 30);

        pfSenha1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        pfSenha1.setEnabled(false);
        pfSenha1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pfSenha1KeyPressed(evt);
            }
        });
        jPanel3.add(pfSenha1);
        pfSenha1.setBounds(330, 560, 110, 30);

        btn_Limpar.setBackground(new java.awt.Color(204, 255, 255));
        btn_Limpar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_Limpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Jail_ts2022/icons/clean.png"))); // NOI18N
        btn_Limpar.setText("Limpar");
        btn_Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LimparActionPerformed(evt);
            }
        });
        btn_Limpar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_LimparKeyPressed(evt);
            }
        });
        jPanel3.add(btn_Limpar);
        btn_Limpar.setBounds(510, 560, 130, 31);

        btn_atualizar.setBackground(new java.awt.Color(204, 255, 255));
        btn_atualizar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_atualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Jail_ts2022/icons/atualizar.png"))); // NOI18N
        btn_atualizar.setText("Editar");
        btn_atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atualizarActionPerformed(evt);
            }
        });
        btn_atualizar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_atualizarKeyPressed(evt);
            }
        });
        jPanel3.add(btn_atualizar);
        btn_atualizar.setBounds(700, 560, 130, 31);

        btn_salvar.setBackground(new java.awt.Color(204, 255, 255));
        btn_salvar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Jail_ts2022/icons/add.png"))); // NOI18N
        btn_salvar.setText("Salvar");
        btn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarActionPerformed(evt);
            }
        });
        btn_salvar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_salvarKeyPressed(evt);
            }
        });
        jPanel3.add(btn_salvar);
        btn_salvar.setBounds(900, 560, 130, 31);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel4.setText("Nome:");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(250, 80, 90, 16);

        txt_Nome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_Nome.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        txt_Nome.setEnabled(false);
        txt_Nome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_NomeKeyPressed(evt);
            }
        });
        jPanel3.add(txt_Nome);
        txt_Nome.setBounds(250, 110, 200, 30);

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Apelido:");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(470, 80, 90, 20);

        txt_Apelido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_Apelido.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        txt_Apelido.setEnabled(false);
        txt_Apelido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ApelidoActionPerformed(evt);
            }
        });
        txt_Apelido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_ApelidoKeyPressed(evt);
            }
        });
        jPanel3.add(txt_Apelido);
        txt_Apelido.setBounds(470, 110, 200, 30);

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Numero de BI:");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(440, 230, 130, 20);

        txt_nbi.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        try {
            txt_nbi.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_nbi.setEnabled(false);
        txt_nbi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_nbi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_nbiKeyPressed(evt);
            }
        });
        jPanel3.add(txt_nbi);
        txt_nbi.setBounds(440, 260, 140, 30);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("ID");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(40, 70, 60, 20);

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Jail_ts2022/icons/manager-icon-png-7 (Copy).jpg"))); // NOI18N
        jButton1.setBorder(null);
        jPanel3.add(jButton1);
        jButton1.setBounds(40, 100, 180, 230);

        tf_contacto.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        try {
            tf_contacto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(+258)  #########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tf_contacto.setEnabled(false);
        tf_contacto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tf_contacto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_contactoKeyPressed(evt);
            }
        });
        jPanel3.add(tf_contacto);
        tf_contacto.setBounds(470, 180, 160, 30);

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Contactos :");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(470, 150, 140, 20);

        tf_nuit.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        try {
            tf_nuit.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tf_nuit.setEnabled(false);
        tf_nuit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tf_nuit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_nuitKeyPressed(evt);
            }
        });
        jPanel3.add(tf_nuit);
        tf_nuit.setBounds(620, 260, 140, 30);

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setText("Nuit:");
        jPanel3.add(jLabel17);
        jLabel17.setBounds(620, 230, 90, 20);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel2.setText("Genero:");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(250, 240, 130, 16);

        buttonGroup1.add(rb_Masculino);
        rb_Masculino.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rb_Masculino.setText("Masculino");
        rb_Masculino.setEnabled(false);
        rb_Masculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_MasculinoActionPerformed(evt);
            }
        });
        rb_Masculino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rb_MasculinoKeyPressed(evt);
            }
        });
        jPanel3.add(rb_Masculino);
        rb_Masculino.setBounds(270, 280, 100, 25);

        buttonGroup1.add(rb_Femenino);
        rb_Femenino.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rb_Femenino.setText("Feminino");
        rb_Femenino.setEnabled(false);
        rb_Femenino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_FemeninoActionPerformed(evt);
            }
        });
        rb_Femenino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rb_FemeninoKeyPressed(evt);
            }
        });
        jPanel3.add(rb_Femenino);
        rb_Femenino.setBounds(270, 320, 100, 25);

        jLabel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(jLabel9);
        jLabel9.setBounds(250, 270, 160, 90);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel3.setText("e-mail");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(50, 430, 140, 20);

        txt_email.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_email.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        txt_email.setEnabled(false);
        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });
        txt_email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_emailKeyPressed(evt);
            }
        });
        jPanel3.add(txt_email);
        txt_email.setBounds(50, 460, 390, 30);

        Ch_dataNascimento.setEnabled(false);
        Ch_dataNascimento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Ch_dataNascimentoKeyPressed(evt);
            }
        });
        jPanel3.add(Ch_dataNascimento);
        Ch_dataNascimento.setBounds(250, 180, 200, 30);

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Data de Nascimento:");
        jPanel3.add(jLabel16);
        jLabel16.setBounds(250, 150, 190, 20);

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("Nacionalidade:");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(820, 90, 130, 20);

        cb_nacionnalidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cabo Delegado", "Niassa", "Nampula", "Zambézia", "Tete", "Manica", "Sofala", "Inhambane", "Gaza", "Maputo Provincia", "Maputo Cidade" }));
        cb_nacionnalidade.setSelectedIndex(-1);
        cb_nacionnalidade.setEnabled(false);
        cb_nacionnalidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_nacionnalidadeActionPerformed(evt);
            }
        });
        cb_nacionnalidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cb_nacionnalidadeKeyPressed(evt);
            }
        });
        jPanel3.add(cb_nacionnalidade);
        cb_nacionnalidade.setBounds(820, 120, 160, 30);

        lbl_Codigo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_Codigo.setForeground(new java.awt.Color(255, 0, 51));
        lbl_Codigo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Codigo.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        jPanel3.add(lbl_Codigo);
        lbl_Codigo.setBounds(110, 70, 110, 25);

        pfSenha2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        pfSenha2.setEnabled(false);
        pfSenha2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pfSenha2KeyPressed(evt);
            }
        });
        jPanel3.add(pfSenha2);
        pfSenha2.setBounds(50, 560, 110, 30);

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Segoe UI", 3, 10)); // NOI18N
        jLabel21.setText("A Senha anterior");
        jPanel3.add(jLabel21);
        jLabel21.setBounds(50, 530, 110, 20);

        lbl_Perfil.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_Perfil.setForeground(new java.awt.Color(255, 51, 51));
        lbl_Perfil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Perfil.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(lbl_Perfil);
        lbl_Perfil.setBounds(440, 330, 180, 30);

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 51, 51));
        jLabel24.setText("Categoria:");
        jPanel3.add(jLabel24);
        jLabel24.setBounds(440, 300, 120, 20);

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setText("Provincia:");
        jPanel3.add(jLabel18);
        jLabel18.setBounds(820, 180, 130, 20);

        cb_naturalidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cabo Delegado", "Niassa", "Nampula", "Zambézia", "Tete", "Manica", "Sofala", "Inhambane", "Gaza", "Maputo Provincia", "Maputo Cidade" }));
        cb_naturalidade.setSelectedIndex(-1);
        cb_naturalidade.setEnabled(false);
        cb_naturalidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_naturalidadeActionPerformed(evt);
            }
        });
        cb_naturalidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cb_naturalidadeKeyPressed(evt);
            }
        });
        jPanel3.add(cb_naturalidade);
        cb_naturalidade.setBounds(820, 210, 160, 30);

        jLabel31.setBackground(new java.awt.Color(204, 204, 204));
        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel31.setText(" ");
        jLabel31.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Local de Residencia ", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 10))); // NOI18N
        jPanel3.add(jLabel31);
        jLabel31.setBounds(790, 60, 240, 230);

        jLabel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        jPanel3.add(jLabel7);
        jLabel7.setBounds(240, 70, 530, 150);

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray), "Meu perfil", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 3, 11))); // NOI18N
        jPanel3.add(jLabel8);
        jLabel8.setBounds(20, 30, 1030, 340);

        jLabel22.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(jLabel22);
        jLabel22.setBounds(10, 20, 1050, 360);

        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(jLabel1);
        jLabel1.setBounds(10, 390, 1050, 210);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1068, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
        );

        setBounds(0, 0, 1072, 638);
    }// </editor-fold>//GEN-END:initComponents

    private void jCsenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCsenhaActionPerformed
        if (jCsenha.isSelected()) {
            pfSenha1.setEchoChar((char) 0);
            pfSenha.setEchoChar((char) 0);
            pfSenha2.setEchoChar((char) 0);
        } else {
            pfSenha.setEchoChar('•');
            pfSenha1.setEchoChar('•');
            pfSenha2.setEchoChar('•');

        }
    }//GEN-LAST:event_jCsenhaActionPerformed
    public void LimparCampos() {

        pfSenha.setText("");
        pfSenha1.setText("");
        buttonGroup1.clearSelection();
    }
    private void btn_LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LimparActionPerformed

        jCsenha.setEnabled(true);

        pfSenha.setEnabled(true);
        pfSenha1.setEnabled(true);
        rb_Femenino.setEnabled(true);
        rb_Masculino.setEnabled(true);
    }//GEN-LAST:event_btn_LimparActionPerformed

    private void btn_LimparKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_LimparKeyPressed
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_LEFT:

                break;
            case KeyEvent.VK_RIGHT:
                break;

        }
    }//GEN-LAST:event_btn_LimparKeyPressed

    private void btn_atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atualizarActionPerformed

        if (btn_atualizar.getText().equalsIgnoreCase("Editar")) {
            btn_atualizar.setText("Atualizar");
            habilitar();
        } else {
            btn_atualizar.setText("Editar");
            //  Atualizar();
        }

    }//GEN-LAST:event_btn_atualizarActionPerformed

    private void btn_atualizarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_atualizarKeyPressed
        switch (evt.getKeyCode()) {

            case KeyEvent.VK_LEFT:

                break;
            case KeyEvent.VK_RIGHT:
                btn_salvar.requestFocus();
                break;

        }
    }//GEN-LAST:event_btn_atualizarKeyPressed

    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarActionPerformed

    }//GEN-LAST:event_btn_salvarActionPerformed

    private void btn_salvarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_salvarKeyPressed
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_LEFT:
                btn_atualizar.requestFocus();
                break;

            case KeyEvent.VK_UP:
                pfSenha.requestFocus();
                break;
        }
    }//GEN-LAST:event_btn_salvarKeyPressed

    private void txt_NomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_NomeKeyPressed
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_ENTER:
                txt_Apelido.requestFocus();
                break;
            case KeyEvent.VK_RIGHT:
                txt_Apelido.requestFocus();
                break;
            case KeyEvent.VK_DOWN:
                Ch_dataNascimento.requestFocus();
                break;
            default:
                break;
        }
    }//GEN-LAST:event_txt_NomeKeyPressed

    private void txt_ApelidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ApelidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ApelidoActionPerformed

    private void txt_ApelidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ApelidoKeyPressed
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_LEFT:
                txt_Nome.requestFocus();
                break;
            case KeyEvent.VK_DOWN:
                tf_contacto.requestFocus();
                break;
            case KeyEvent.VK_ENTER:
                txt_nbi.requestFocus();
                break;
            case KeyEvent.VK_RIGHT:
                txt_nbi.requestFocus();
                break;
            default:
                break;
        }
    }//GEN-LAST:event_txt_ApelidoKeyPressed

    private void txt_nbiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nbiKeyPressed
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_DOWN:
                tf_contacto.requestFocus();
                break;
            case KeyEvent.VK_RIGHT:
                Ch_dataNascimento.requestFocus();
                break;
            case KeyEvent.VK_ENTER:
                Ch_dataNascimento.requestFocus();
                break;
            case KeyEvent.VK_LEFT:
                txt_Apelido.requestFocus();
                break;
            default:
                break;
        }
    }//GEN-LAST:event_txt_nbiKeyPressed

    private void tf_contactoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_contactoKeyPressed
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_UP:
                txt_nbi.requestFocus();
                break;
            case KeyEvent.VK_DOWN:

                break;
            case KeyEvent.VK_LEFT:
                tf_nuit.requestFocus();
                break;
            case KeyEvent.VK_RIGHT:
                // tf_contactoSecundario.requestFocus();
                break;
            case KeyEvent.VK_ENTER:
                // tf_contactoSecundario.requestFocus();
                break;
            default:
                break;
        }
    }//GEN-LAST:event_tf_contactoKeyPressed

    private void tf_nuitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_nuitKeyPressed
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_UP:
                txt_Apelido.requestFocus();
                break;
            case KeyEvent.VK_DOWN:
                rb_Masculino.requestFocus();
                break;
            case KeyEvent.VK_RIGHT:
                tf_contacto.requestFocus();
                break;
            case KeyEvent.VK_LEFT:
                Ch_dataNascimento.requestFocus();
                break;
            case KeyEvent.VK_ENTER:
                tf_contacto.requestFocus();
                break;
            default:
                break;
        }
    }//GEN-LAST:event_tf_nuitKeyPressed

    private void rb_MasculinoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rb_MasculinoKeyPressed
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_UP:
                tf_nuit.requestFocus();
                break;
            case KeyEvent.VK_DOWN:
                rb_Femenino.requestFocus();
                break;
            case KeyEvent.VK_LEFT:
//                tf_contactoSecundario.requestFocus();
                break;
            case KeyEvent.VK_RIGHT:

                break;
            case KeyEvent.VK_ENTER:
                rb_Masculino.setSelected(true);

                break;
            default:
                break;
        }
    }//GEN-LAST:event_rb_MasculinoKeyPressed

    private void rb_FemeninoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rb_FemeninoKeyPressed
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_UP:
                rb_Masculino.requestFocus();
                break;
            case KeyEvent.VK_DOWN:
                txt_email.requestFocus();
                break;
            case KeyEvent.VK_LEFT:
//                tf_contactoSecundario.requestFocus();
                break;
            case KeyEvent.VK_RIGHT:

                break;
            case KeyEvent.VK_ENTER:
                rb_Femenino.setSelected(true);

                break;
            default:
                break;
        }
    }//GEN-LAST:event_rb_FemeninoKeyPressed

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailActionPerformed

    private void txt_emailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_emailKeyPressed
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_UP:
                rb_Femenino.requestFocus();
                break;
            case KeyEvent.VK_LEFT:

                break;
            case KeyEvent.VK_RIGHT:
                pfSenha.requestFocus();
                break;
            case KeyEvent.VK_ENTER:
                pfSenha.requestFocus();
                break;
            default:
                break;
        }
    }//GEN-LAST:event_txt_emailKeyPressed

    private void Ch_dataNascimentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Ch_dataNascimentoKeyPressed
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_UP:
                txt_Nome.requestFocus();
                break;
            case KeyEvent.VK_DOWN:
//                tf_contactoSecundario.requestFocus();
                break;

            case KeyEvent.VK_RIGHT:
                tf_nuit.requestFocus();
                break;
            case KeyEvent.VK_LEFT:
                if (rb_Masculino.equals("Masculino")) {
                    rb_Masculino.setSelected(true);
                } else if (rb_Femenino.equals("Feminino")) {
                    rb_Femenino.setSelected(true);
                }
                break;
            case KeyEvent.VK_ENTER:
                tf_nuit.requestFocus();
                break;
            default:
                break;
        }
    }//GEN-LAST:event_Ch_dataNascimentoKeyPressed

    private void cb_nacionnalidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cb_nacionnalidadeKeyPressed
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_UP:
//                tf_contactoSecundario.requestFocus();
                break;

            case KeyEvent.VK_ENTER:

                cb_nacionnalidade.getSelectedItem();

                break;
            default:
                break;
        }
    }//GEN-LAST:event_cb_nacionnalidadeKeyPressed

    private void rb_MasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_MasculinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_MasculinoActionPerformed

    private void rb_FemeninoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_FemeninoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_FemeninoActionPerformed

    private void pfSenha1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pfSenha1KeyPressed
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_UP:
                txt_email.requestFocus();
                break;
            case KeyEvent.VK_LEFT:
                pfSenha.requestFocus();
                break;
            case KeyEvent.VK_RIGHT:
                btn_salvar.requestFocus();
                break;
            case KeyEvent.VK_ENTER:
                btn_salvar.requestFocus();
                break;
            default:
                break;
        }
    }//GEN-LAST:event_pfSenha1KeyPressed

    private void pfSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pfSenhaKeyPressed
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_UP:
                txt_email.requestFocus();
                break;
            case KeyEvent.VK_LEFT:
                txt_email.requestFocus();
                break;
            case KeyEvent.VK_RIGHT:
                pfSenha1.requestFocus();
                break;
            case KeyEvent.VK_ENTER:
                pfSenha1.requestFocus();
                break;
            default:
                break;
        }
    }//GEN-LAST:event_pfSenhaKeyPressed

    private void pfSenha2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pfSenha2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfSenha2KeyPressed

    private void cb_nacionnalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_nacionnalidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_nacionnalidadeActionPerformed

    private void cb_naturalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_naturalidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_naturalidadeActionPerformed

    private void cb_naturalidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cb_naturalidadeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_naturalidadeKeyPressed

    private void pfSenhaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pfSenhaKeyReleased
//        if (pf_Senha.getText().equals(pf_SenhaConfimar.getText())) {
//            pf_Senha.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.GREEN));
//            pf_SenhaConfimar.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.GREEN));
//
//        } else {
//            pf_SenhaConfimar.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.red));
//
//        }
    }//GEN-LAST:event_pfSenhaKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Ch_dataNascimento;
    private javax.swing.JButton btn_Limpar;
    private javax.swing.JButton btn_atualizar;
    private javax.swing.JButton btn_salvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cb_nacionnalidade;
    private javax.swing.JComboBox<String> cb_naturalidade;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCsenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbl_Codigo;
    private javax.swing.JLabel lbl_Perfil;
    private javax.swing.JPasswordField pfSenha;
    private javax.swing.JPasswordField pfSenha1;
    private javax.swing.JPasswordField pfSenha2;
    private javax.swing.JRadioButton rb_Femenino;
    private javax.swing.JRadioButton rb_Masculino;
    private javax.swing.JFormattedTextField tf_contacto;
    private javax.swing.JFormattedTextField tf_nuit;
    private javax.swing.JTextField txt_Apelido;
    private javax.swing.JTextField txt_Nome;
    private javax.swing.JTextField txt_email;
    private javax.swing.JFormattedTextField txt_nbi;
    // End of variables declaration//GEN-END:variables

}
