/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Jail_ts2022.views;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.net.URL;
import java.time.YearMonth;
import java.util.List;
import java.util.regex.Pattern;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import Jail_ts2022.controller.ControllerFuncionario;
import Jail_ts2022.dao.DirectorDao;
import Jail_ts2022.dao.FuncionarioDao;
import Jail_ts2022.dao.NivelDeAcessoDao;
import Jail_ts2022.dao.ProvinciasDAo;
import Jail_ts2022.model.NivelDeAcesso;
import Jail_ts2022.model.Funcionario;
import Jail_ts2022.model.Provincias;

/**
 *
 * @author Mutisse
 */
public final class TelaRegistoDirector extends javax.swing.JFrame {

    ControllerFuncionario f = new ControllerFuncionario();

    /**
     * Creates new form RegistoUsuario
     */
    public TelaRegistoDirector() {
        initComponents();
        setIconImage();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    void setarcodigo() {
        FuncionarioDao Dao = new FuncionarioDao();
        String str = String.valueOf(Dao.gerarCodigo());
        int itg = Integer.parseInt(str);
        //
        lbl_Codigo.setText(String.valueOf(YearMonth.now().getYear() + "" + itg));

    }

    void cb_provincia() {
        cb_provincias.removeAllItems();
        for (int i = 0; i < listarProvincia.size(); i++) {

            cb_provincias.addItem(listarProvincia.get(i));

        }

    }

    void preencherPerfil() {
        NivelDeAcessoDao nivel = new NivelDeAcessoDao();
        List<NivelDeAcesso> niveldeAcesso = nivel.ListarNivelDeAcesso();

        for (int i = 0; i < niveldeAcesso.size(); i++) {
            if (niveldeAcesso.get(i).getCategoria().equalsIgnoreCase("Director geral")) {
                cb_perfil.addItem(niveldeAcesso.get(i));

            }

        }
    }

    void validacaoDosCampos() {
        if (txt_Nome.getText().isEmpty()) {
            btnRegistar.setEnabled(false);
            JOptionPane.showMessageDialog(null, "O Campo  Nome deve Ser Preenchido!", "Atenção", JOptionPane.WARNING_MESSAGE);
        } else if (txt_Apelido.getText().isEmpty()) {
            btnRegistar.setEnabled(false);
            JOptionPane.showMessageDialog(null, "O Campo Apelido Deve  Ser Preenchido!", "Atenção", JOptionPane.WARNING_MESSAGE);
        } else if (txt_email.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "O Campo e-mail Deve Ser Preenchido!", "Atenção", JOptionPane.WARNING_MESSAGE);
            btnRegistar.setEnabled(false);
        } else if (pf_definirAsenha.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "O Campo senha Deve Ser Preenchido!", "Atenção", JOptionPane.WARNING_MESSAGE);
            btnRegistar.setEnabled(false);
        } else if (rb_Masculino.getActionCommand().isEmpty() || rb_Femenino.getActionCommand().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Não foi seleccionada nenhuma Categoria!", "Atenção", JOptionPane.WARNING_MESSAGE);

            btnRegistar.setEnabled(false);
        } else {
            btnRegistar.setEnabled(true);
            registrar();
        }
    }

    void registrar() {

        try {
            if (txt_Apelido.getText().isEmpty() || txt_Nome.getText().isEmpty() || (rb_Masculino.getActionCommand().isEmpty() && rb_Masculino.getActionCommand().isEmpty()) || txt_email.getText().isEmpty() || pf_ConfirmarAsenha.getText().isEmpty() || pf_definirAsenha.getText().isEmpty()) {

                JOptionPane.showMessageDialog(null, "Preencha todos campos obrigatorios");
            } else {
                if (pf_definirAsenha.getText().length() > 3 || pf_ConfirmarAsenha.getText().length() > 3) {

                    director.setSenha(pf_definirAsenha.getText());
                    director.setApelido(txt_Apelido.getText());
                    director.setCodigo(lbl_Codigo.getText());
                    director.setNome(txt_Nome.getText());
                    if (rb_Masculino.isSelected()) {
                        director.setGenero(rb_Masculino.getActionCommand());
                    } else if (rb_Femenino.isSelected()) {
                        director.setGenero(rb_Femenino.getActionCommand());
                    }

                    director.setEmail(txt_email.getText());
                    director.setNivelDeAcesso((NivelDeAcesso) cb_perfil.getSelectedItem());
                    director.setProvincia((Provincias) cb_provincias.getSelectedItem());

                    directorDao.savarDirector(director);
                    limparCampos();
                    this.dispose();
                    new TelaLogin().setVisible(true);

                } else {

                    JOptionPane.showMessageDialog(null, "Senha inválida.\nCombine pelo menos 4 caracteres!", "Notificacao", JOptionPane.INFORMATION_MESSAGE);
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e + " Erro problema na digitação dos dados ", "Notificação", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }

    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jRadioButton = new javax.swing.JRadioButton();
        painel9 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnLimpar = new javax.swing.JButton();
        txt_Apelido = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_Nome = new javax.swing.JTextField();
        btnRegistar = new javax.swing.JButton();
        btnLimpar1 = new javax.swing.JButton();
        rb_Masculino = new javax.swing.JRadioButton();
        rb_Femenino = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jCsenha = new javax.swing.JCheckBox();
        pf_definirAsenha = new javax.swing.JPasswordField();
        pf_ConfirmarAsenha = new javax.swing.JPasswordField();
        lbl_Codigo = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        cb_perfil = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        cb_provincias = new javax.swing.JComboBox<>();

        jRadioButton.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        painel9.setBackground(new java.awt.Color(204, 204, 204));
        painel9.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registro de Director Geral");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        painel9.add(jLabel1);
        jLabel1.setBounds(50, 20, 420, 40);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Género:");
        painel9.add(jLabel2);
        jLabel2.setBounds(320, 250, 90, 20);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("* e-mail para Login:");
        painel9.add(jLabel3);
        jLabel3.setBounds(40, 160, 180, 20);

        btnLimpar.setBackground(new java.awt.Color(204, 255, 255));
        btnLimpar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Jail_ts2022/icons/Cancel.png"))); // NOI18N
        btnLimpar.setText("Cancelar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        painel9.add(btnLimpar);
        btnLimpar.setBounds(60, 440, 150, 31);

        txt_Apelido.setBackground(new java.awt.Color(204, 204, 204));
        txt_Apelido.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_Apelido.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        txt_Apelido.setEnabled(false);
        txt_Apelido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ApelidoActionPerformed(evt);
            }
        });
        txt_Apelido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_ApelidoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_ApelidoKeyTyped(evt);
            }
        });
        painel9.add(txt_Apelido);
        txt_Apelido.setBounds(280, 110, 200, 30);

        txt_email.setBackground(new java.awt.Color(204, 204, 204));
        txt_email.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_email.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        txt_email.setEnabled(false);
        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });
        txt_email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_emailKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_emailKeyTyped(evt);
            }
        });
        painel9.add(txt_email);
        txt_email.setBounds(40, 190, 250, 30);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("* Senha:");
        painel9.add(jLabel5);
        jLabel5.setBounds(40, 300, 79, 20);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("* Confirmar senha:");
        painel9.add(jLabel6);
        jLabel6.setBounds(150, 300, 102, 20);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("* Apelido:");
        painel9.add(jLabel7);
        jLabel7.setBounds(270, 80, 90, 20);

        txt_Nome.setBackground(new java.awt.Color(204, 204, 204));
        txt_Nome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_Nome.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        txt_Nome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_NomeKeyPressed(evt);
            }
        });
        painel9.add(txt_Nome);
        txt_Nome.setBounds(40, 110, 200, 30);

        btnRegistar.setBackground(new java.awt.Color(204, 255, 255));
        btnRegistar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnRegistar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Jail_ts2022/icons/add.png"))); // NOI18N
        btnRegistar.setText("Registar");
        btnRegistar.setEnabled(false);
        btnRegistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistarActionPerformed(evt);
            }
        });
        btnRegistar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnRegistarKeyPressed(evt);
            }
        });
        painel9.add(btnRegistar);
        btnRegistar.setBounds(460, 440, 130, 31);

        btnLimpar1.setBackground(new java.awt.Color(204, 255, 255));
        btnLimpar1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLimpar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projecto001/views/icons/clean.png"))); // NOI18N
        btnLimpar1.setText("Limpar");
        btnLimpar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpar1ActionPerformed(evt);
            }
        });
        painel9.add(btnLimpar1);
        btnLimpar1.setBounds(250, 440, 160, 31);

        buttonGroup.add(rb_Masculino);
        rb_Masculino.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rb_Masculino.setText("Masculino");
        rb_Masculino.setEnabled(false);
        rb_Masculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_MasculinoActionPerformed(evt);
            }
        });
        rb_Masculino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rb_MasculinoKeyPressed(evt);
            }
        });
        painel9.add(rb_Masculino);
        rb_Masculino.setBounds(340, 290, 100, 25);

        buttonGroup.add(rb_Femenino);
        rb_Femenino.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rb_Femenino.setText("Femenino");
        rb_Femenino.setEnabled(false);
        rb_Femenino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rb_FemeninoKeyPressed(evt);
            }
        });
        painel9.add(rb_Femenino);
        rb_Femenino.setBounds(340, 320, 100, 25);

        jLabel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        painel9.add(jLabel9);
        jLabel9.setBounds(320, 280, 140, 80);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("* Nome:");
        painel9.add(jLabel4);
        jLabel4.setBounds(40, 80, 90, 20);

        jCsenha.setBackground(new java.awt.Color(204, 204, 204));
        jCsenha.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jCsenha.setText("Mostrar a Senha ");
        jCsenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCsenhaActionPerformed(evt);
            }
        });
        painel9.add(jCsenha);
        jCsenha.setBounds(40, 370, 130, 21);

        pf_definirAsenha.setBackground(new java.awt.Color(204, 204, 204));
        pf_definirAsenha.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        pf_definirAsenha.setEnabled(false);
        pf_definirAsenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pf_definirAsenhaKeyPressed(evt);
            }
        });
        painel9.add(pf_definirAsenha);
        pf_definirAsenha.setBounds(40, 330, 100, 30);

        pf_ConfirmarAsenha.setBackground(new java.awt.Color(204, 204, 204));
        pf_ConfirmarAsenha.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        pf_ConfirmarAsenha.setEnabled(false);
        pf_ConfirmarAsenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pf_ConfirmarAsenhaActionPerformed(evt);
            }
        });
        pf_ConfirmarAsenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pf_ConfirmarAsenhaKeyPressed(evt);
            }
        });
        painel9.add(pf_ConfirmarAsenha);
        pf_ConfirmarAsenha.setBounds(160, 330, 100, 30);

        lbl_Codigo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_Codigo.setForeground(new java.awt.Color(255, 0, 51));
        lbl_Codigo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Codigo.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        painel9.add(lbl_Codigo);
        lbl_Codigo.setBounds(560, 60, 90, 25);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel10.setText("Codigo");
        painel9.add(jLabel10);
        jLabel10.setBounds(500, 60, 50, 20);
        painel9.add(jSeparator1);
        jSeparator1.setBounds(30, 420, 630, 60);

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("* campos obrigatorios ");
        painel9.add(jLabel15);
        jLabel15.setBounds(520, 10, 150, 20);

        cb_perfil.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cb_perfil.setToolTipText("");
        cb_perfil.setEnabled(false);
        cb_perfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_perfilActionPerformed(evt);
            }
        });
        cb_perfil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cb_perfilKeyPressed(evt);
            }
        });
        painel9.add(cb_perfil);
        cb_perfil.setBounds(320, 190, 160, 30);

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("* Categoria:");
        painel9.add(jLabel16);
        jLabel16.setBounds(320, 160, 100, 20);

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setText("*Provincia:");
        painel9.add(jLabel18);
        jLabel18.setBounds(40, 230, 130, 20);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Jail_ts2022/icons/est.png"))); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray));
        painel9.add(jButton1);
        jButton1.setBounds(510, 100, 140, 170);

        cb_provincias.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cb_provincias.setEnabled(false);
        cb_provincias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_provinciasActionPerformed(evt);
            }
        });
        cb_provincias.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cb_provinciasKeyPressed(evt);
            }
        });
        painel9.add(cb_provincias);
        cb_provincias.setBounds(40, 260, 200, 30);

        getContentPane().add(painel9);
        painel9.setBounds(0, 0, 680, 490);

        setSize(new java.awt.Dimension(677, 487));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cb_perfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_perfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_perfilActionPerformed

    private void pf_ConfirmarAsenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pf_ConfirmarAsenhaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (pf_definirAsenha.getText().equalsIgnoreCase(pf_ConfirmarAsenha.getText())) {
                pf_definirAsenha.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.GREEN));
                pf_ConfirmarAsenha.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.GREEN));
                btnRegistar.setEnabled(true);
                rb_Masculino.requestFocus();

            } else {
                pf_ConfirmarAsenha.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.red));
                btnRegistar.setEnabled(false);

            }

        } else if (evt.getKeyCode() == KeyEvent.VK_BACK_SPACE) {
            pf_ConfirmarAsenha.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.BLACK));
        }
    }//GEN-LAST:event_pf_ConfirmarAsenhaKeyPressed

    private void pf_ConfirmarAsenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pf_ConfirmarAsenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pf_ConfirmarAsenhaActionPerformed

    private void pf_definirAsenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pf_definirAsenhaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (pf_definirAsenha.getText().length() > 3 || pf_ConfirmarAsenha.getText().length() > 3) {
                pf_ConfirmarAsenha.setEnabled(true);
                pf_ConfirmarAsenha.requestFocus();

            } else {
                pf_definirAsenha.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.red));
                pf_definirAsenha.requestFocus();
                JOptionPane.showMessageDialog(null, "Senha inválida.\nCombine pelo menos 4 caracteres!", "Notificacao", JOptionPane.INFORMATION_MESSAGE);
            }
        } else if (evt.getKeyCode() == KeyEvent.VK_BACK_SPACE) {
            pf_ConfirmarAsenha.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.BLACK));
        }


    }//GEN-LAST:event_pf_definirAsenhaKeyPressed

    private void jCsenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCsenhaActionPerformed
        if (jCsenha.isSelected()) {
            pf_ConfirmarAsenha.setEchoChar((char) 0);
            pf_definirAsenha.setEchoChar((char) 0);
        } else {
            pf_definirAsenha.setEchoChar('•');
            pf_ConfirmarAsenha.setEchoChar('•');

        }
    }//GEN-LAST:event_jCsenhaActionPerformed

    private void rb_FemeninoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rb_FemeninoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            rb_Femenino.isSelected();
            btnRegistar.requestFocus();
        }
        if (evt.getKeyCode() == KeyEvent.VK_UP) {
            rb_Femenino.requestFocus();
        }
    }//GEN-LAST:event_rb_FemeninoKeyPressed

    private void rb_MasculinoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rb_MasculinoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            rb_Masculino.isSelected();
            btnRegistar.requestFocus();
        }
        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            rb_Femenino.requestFocus();
        }


    }//GEN-LAST:event_rb_MasculinoKeyPressed

    private void rb_MasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_MasculinoActionPerformed

    }//GEN-LAST:event_rb_MasculinoActionPerformed

    private void btnLimpar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpar1ActionPerformed
        limparCampos();
    }//GEN-LAST:event_btnLimpar1ActionPerformed

    private void btnRegistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistarActionPerformed
        validacaoDosCampos();
    }//GEN-LAST:event_btnRegistarActionPerformed

    private void txt_NomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_NomeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (Pattern.matches("^[a-zA-Z]+$", txt_Nome.getText())) {
                txt_Nome.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.GREEN));
                txt_Apelido.requestFocus();
                txt_Apelido.setEnabled(true);
                setarcodigo();
                preencherPerfil();
                cb_provincia();

            } else {
                txt_Nome.requestFocus();
                txt_Nome.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.red));
                txt_Apelido.setEnabled(false);
                txt_email.setEnabled(false);
                pf_definirAsenha.setEnabled(false);
                rb_Masculino.setEnabled(false);
                rb_Femenino.setEnabled(false);
            }

        } else if (evt.getKeyCode() == KeyEvent.VK_BACK_SPACE) {
            txt_Nome.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.BLACK));

        }
    }//GEN-LAST:event_txt_NomeKeyPressed

    private void txt_emailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_emailKeyTyped

    }//GEN-LAST:event_txt_emailKeyTyped

    private void txt_emailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_emailKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            if (f.validarEmail(txt_email.getText()) == false) {
                txt_email.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.red));
                pf_definirAsenha.setEnabled(false);
                pf_ConfirmarAsenha.setEnabled(false);
            } else {
                pf_definirAsenha.setEnabled(true);
                rb_Masculino.setEnabled(true);
                rb_Femenino.setEnabled(true);
                cb_provincias.setEnabled(true);
                cb_perfil.setEnabled(true);
                cb_perfil.requestFocus();
                txt_email.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.GREEN));

            }

        } else if (evt.getKeyCode() == KeyEvent.VK_BACK_SPACE) {
            txt_email.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.BLACK));
        }


    }//GEN-LAST:event_txt_emailKeyPressed

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailActionPerformed

    private void txt_ApelidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ApelidoKeyTyped

    }//GEN-LAST:event_txt_ApelidoKeyTyped

    private void txt_ApelidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ApelidoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (Pattern.matches("^[a-zA-Z]+$", txt_Apelido.getText())) {

                txt_Apelido.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.GREEN));
                txt_email.requestFocus();
                txt_email.setEnabled(true);

            } else {
                txt_Apelido.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.red));
                txt_email.setEnabled(false);
                pf_definirAsenha.setEnabled(false);
                rb_Masculino.setEnabled(false);
                rb_Femenino.setEnabled(false);

            }
        } else if (evt.getKeyCode() == KeyEvent.VK_BACK_SPACE) {
            txt_Apelido.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.BLACK));
        }

    }//GEN-LAST:event_txt_ApelidoKeyPressed

    private void txt_ApelidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ApelidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ApelidoActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        this.dispose();
        new TelaLogin().setVisible(true);
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnRegistarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnRegistarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            validacaoDosCampos();

        }
    }//GEN-LAST:event_btnRegistarKeyPressed

    private void cb_provinciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_provinciasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_provinciasActionPerformed

    private void cb_perfilKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cb_perfilKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            cb_provincias.requestFocus();
        }
    }//GEN-LAST:event_cb_perfilKeyPressed

    private void cb_provinciasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cb_provinciasKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            pf_definirAsenha.requestFocus();
        }
    }//GEN-LAST:event_cb_provinciasKeyPressed

    void limparCampos() {
        txt_Nome.setText(null);
        txt_Apelido.setText(null);
        txt_email.setText(null);
        pf_definirAsenha.setText(null);
        pf_ConfirmarAsenha.setText(null);
        lbl_Codigo.setText(null);
        buttonGroup.clearSelection();
        txt_Nome.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.BLACK));
        txt_Apelido.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.BLACK));
        txt_email.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.BLACK));
        desabilitar();
    }

    void desabilitar() {
        txt_email.setEnabled(false);
        txt_Apelido.setEnabled(false);
        pf_definirAsenha.setEnabled(false);
        pf_ConfirmarAsenha.setEnabled(false);
        rb_Masculino.setEnabled(false);
        cb_perfil.setEnabled(false);
        rb_Femenino.setEnabled(false);
    }

    /**
     * @param args the command line arguments //
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        <editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TelaRegistoDirector.class
//                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
//
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TelaRegistoDirector.class
//                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
//
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TelaRegistoDirector.class
//                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
//
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TelaRegistoDirector.class
//                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        </editor-fold>
//        </editor-fold>
//        </editor-fold>
//        </editor-fold>
//        </editor-fold>
//        </editor-fold>
//        </editor-fold>
//        </editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new TelaRegistoDirector().setVisible(true);
//            }
//        });
//    }
//    private String captoSenha;

    DirectorDao directorDao = new DirectorDao();
    Funcionario director = new Funcionario();
    ProvinciasDAo provincia = new ProvinciasDAo();
    List<Provincias> listarProvincia = provincia.ListaProvincias();
    //
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnLimpar1;
    private javax.swing.JButton btnRegistar;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JComboBox<Jail_ts2022.model.NivelDeAcesso> cb_perfil;
    private javax.swing.JComboBox<Jail_ts2022.model.Provincias> cb_provincias;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCsenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_Codigo;
    private javax.swing.JPanel painel9;
    private javax.swing.JPasswordField pf_ConfirmarAsenha;
    private javax.swing.JPasswordField pf_definirAsenha;
    private javax.swing.JRadioButton rb_Femenino;
    private javax.swing.JRadioButton rb_Masculino;
    private javax.swing.JTextField txt_Apelido;
    private javax.swing.JTextField txt_Nome;
    private javax.swing.JTextField txt_email;
    // End of variables declaration//GEN-END:variables

    void setIconImage() {
        URL url = this.getClass().getResource("/Jail_ts2022/icons/est.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(iconeTitulo);
    }
}
