/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Jail_ts2022.views;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import Jail_ts2022.conexao.Conectar;
import Jail_ts2022.controller.ControllerFuncionario;
import Jail_ts2022.model.NivelDeAcesso;
import Jail_ts2022.model.Funcionario;
import Jail_ts2022.model.Provincias;

/**
 *
 * @author Mutisse
 */
public final class TelaLogin extends javax.swing.JFrame {
    // variaves de conexao

    Connection conexao = null;
    PreparedStatement stat = null; //pst quer dizer  PreparedStatement
    ResultSet rst = null;
    ControllerFuncionario f = new ControllerFuncionario();
//

    /**
     * Creates new form Login
     */
    public TelaLogin() {
        initComponents();
        txt_Username.requestFocus();
        btn_entrar.setEnabled(false);
        btn_ocultar.setVisible(false);
        btn_ver.setVisible(false);
        lbl_recuperarSenha.setVisible(false);

        setIconImage();
        lbl_imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Jail_ts2022/icons/Senha.png")));
        //

        conexao = Conectar.conector();
        if (conexao != null) {

            lbl_Conexao.setToolTipText(" Conectado Com a Banco de Dados");
            lbl_Conexao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Jail_ts2022/icons/conectado.png")));

        } else {
            lbl_auteticaca.setVisible(false);
            lbl_Conexao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Jail_ts2022/icons/deconectado.png")));
            lbl_Conexao.setToolTipText(" Erro na conecção Com o Banco de Dados, o servidor esta desligado ");

        }

        horaData();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_imagem = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jlbl_Icone = new javax.swing.JLabel();
        txtp_senha = new javax.swing.JPasswordField();
        txt_Username = new javax.swing.JTextField();
        lbl_iconSenha = new javax.swing.JLabel();
        lbl_iconUser = new javax.swing.JLabel();
        btn_ocultar = new javax.swing.JButton();
        btn_ver = new javax.swing.JButton();
        btn_entrar = new javax.swing.JButton();
        lbl_auteticaca = new javax.swing.JLabel();
        lbl_Conexao = new javax.swing.JLabel();
        lbl_recuperarSenha = new javax.swing.JLabel();
        lbl_boasVindas = new javax.swing.JLabel();
        lbl_horaData = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_border = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(" Login");
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(214, 217, 223));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray));
        jPanel1.setLayout(null);

        lbl_imagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbl_imagem);
        lbl_imagem.setBounds(20, 111, 190, 210);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setLayout(null);

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Jail_ts2022/icons/Cancel.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(502, 5, 32, 22);

        jlbl_Icone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Jail_ts2022/icons/Senha3.png"))); // NOI18N
        jPanel2.add(jlbl_Icone);
        jlbl_Icone.setBounds(6, 2, 27, 22);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 540, 30);

        txtp_senha.setBackground(new java.awt.Color(214, 217, 223));
        txtp_senha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtp_senha.setText("123456");
        txtp_senha.setToolTipText("A sua senha ");
        txtp_senha.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 255, 255)));
        txtp_senha.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtp_senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtp_senhaActionPerformed(evt);
            }
        });
        txtp_senha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtp_senhaKeyPressed(evt);
            }
        });
        jPanel1.add(txtp_senha);
        txtp_senha.setBounds(300, 261, 180, 30);

        txt_Username.setBackground(new java.awt.Color(214, 217, 223));
        txt_Username.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_Username.setText("albertonhssg2@gmail.com");
        txt_Username.setToolTipText("O email  deve conter @ dominio.com");
        txt_Username.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 255, 255)));
        txt_Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_UsernameActionPerformed(evt);
            }
        });
        txt_Username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_UsernameKeyPressed(evt);
            }
        });
        jPanel1.add(txt_Username);
        txt_Username.setBounds(300, 211, 180, 30);

        lbl_iconSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Jail_ts2022/icons/senhaLogin.png"))); // NOI18N
        lbl_iconSenha.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 255, 255)));
        jPanel1.add(lbl_iconSenha);
        lbl_iconSenha.setBounds(270, 261, 30, 30);

        lbl_iconUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Jail_ts2022/icons/userLogin.png"))); // NOI18N
        lbl_iconUser.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 255, 255)));
        jPanel1.add(lbl_iconUser);
        lbl_iconUser.setBounds(270, 211, 30, 30);

        btn_ocultar.setBackground(new java.awt.Color(214, 217, 223));
        btn_ocultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Jail_ts2022/icons/ocultar.png"))); // NOI18N
        btn_ocultar.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        btn_ocultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ocultarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_ocultar);
        btn_ocultar.setBounds(480, 260, 32, 25);

        btn_ver.setBackground(new java.awt.Color(214, 217, 223));
        btn_ver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Jail_ts2022/icons/visualizar.png"))); // NOI18N
        btn_ver.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        btn_ver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_verActionPerformed(evt);
            }
        });
        jPanel1.add(btn_ver);
        btn_ver.setBounds(480, 260, 32, 25);

        btn_entrar.setBackground(new java.awt.Color(204, 255, 255));
        btn_entrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_entrar.setForeground(new java.awt.Color(51, 51, 51));
        btn_entrar.setText("iniciar");
        btn_entrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_entrarMouseEntered(evt);
            }
        });
        btn_entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_entrarActionPerformed(evt);
            }
        });
        btn_entrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_entrarKeyPressed(evt);
            }
        });
        jPanel1.add(btn_entrar);
        btn_entrar.setBounds(330, 330, 120, 29);

        lbl_auteticaca.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_auteticaca.setForeground(new java.awt.Color(153, 153, 153));
        lbl_auteticaca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_auteticaca.setText("Autenticação");
        lbl_auteticaca.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(lbl_auteticaca);
        lbl_auteticaca.setBounds(290, 101, 190, 40);
        jPanel1.add(lbl_Conexao);
        lbl_Conexao.setBounds(10, 40, 40, 50);

        lbl_recuperarSenha.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        lbl_recuperarSenha.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_recuperarSenha.setText("Recuperar a senha ");
        lbl_recuperarSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_recuperarSenhaMouseClicked(evt);
            }
        });
        lbl_recuperarSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lbl_recuperarSenhaKeyPressed(evt);
            }
        });
        jPanel1.add(lbl_recuperarSenha);
        lbl_recuperarSenha.setBounds(360, 301, 100, 13);

        lbl_boasVindas.setFont(new java.awt.Font("Yu Gothic UI Semilight", 3, 18)); // NOI18N
        lbl_boasVindas.setForeground(new java.awt.Color(153, 153, 153));
        jPanel1.add(lbl_boasVindas);
        lbl_boasVindas.setBounds(10, 330, 100, 20);

        lbl_horaData.setFont(new java.awt.Font("Segoe UI", 3, 10)); // NOI18N
        lbl_horaData.setForeground(new java.awt.Color(153, 153, 153));
        jPanel1.add(lbl_horaData);
        lbl_horaData.setBounds(10, 360, 230, 18);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 1, 0, 0);

        lbl_border.setBackground(new java.awt.Color(204, 255, 255));
        lbl_border.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray), "Login", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 3, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.add(lbl_border);
        lbl_border.setBounds(240, 31, 290, 350);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(538, 389));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
Timer tm;

    /**
     * ************************ Metodos ***************************
     */
    void camposVazios() {
        if (txt_Username.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Introduza o seu e-mail", "", JOptionPane.INFORMATION_MESSAGE);
            btn_entrar.setEnabled(false);
            btn_ver.setVisible(false);
            txtp_senha.setEnabled(false);
            txt_Username.requestFocus();
        } else {
            btn_ver.setVisible(true);
            txtp_senha.requestFocus();
            if (!txtp_senha.getText().isBlank()) {
                logar();
            } else {
                JOptionPane.showMessageDialog(null, "Introduza a sua senha!", "", JOptionPane.INFORMATION_MESSAGE);
                btn_entrar.setEnabled(false);
            }
        }
    }

    void horaData() {
        Date data = new Date();
        sdf = new SimpleDateFormat("dd MMMM yyyy");
        Calendar now = Calendar.getInstance();
        class hora implements ActionListener {

            @Override
            public void actionPerformed(ActionEvent e) {
                Calendar now = Calendar.getInstance();
                lbl_horaData.setText(String.format("Data: " + sdf.format(data) + ",  Horas:  " + "%1$tH : %1$tM : %1$tS", now));

            }

        }

        Timer timer = new Timer(1000, new hora());
        timer.start();
        Calendar c1 = Calendar.getInstance();
        int hora = c1.get(Calendar.HOUR_OF_DAY);

        if (hora <= 12 && hora <= 12) {
            lbl_boasVindas.setText("Bom Dia");
        } else if (hora > 12 && hora < 18) {
            lbl_boasVindas.setText("Boa Tarde");
        } else {
            lbl_boasVindas.setText("Boa Noite");
        }

    }

    void entrar() {
        int confrimar = JOptionPane.showConfirmDialog(null, "Deseja recuparar a conta? ", "", JOptionPane.YES_NO_OPTION);
        if (confrimar == JOptionPane.YES_OPTION) {
            this.dispose();
            new recuperarConta().setVisible(true);
        } else {
            System.exit(0);
        }
    }

    void limparCampos() {
        txtp_senha.setText(null);
        txt_Username.setText(null);
        txt_Username.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, new Color(204, 255, 255)));
        lbl_iconUser.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, new Color(204, 255, 255)));
        //
        lbl_iconSenha.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, new Color(204, 255, 255)));
        txtp_senha.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, new Color(204, 255, 255)));

    }

    void logar() {

        String SQL = "select * from tbfuncionario LEFT join tbcategoria on tbfuncionario.tbcategoria_id_categoria = tbcategoria.id_categoria LEFT join tbprovincias on tbprovincias.id_Provincias=tbfuncionario.tbprovincias_id_Provincias where email = ? and Senha=?";
        try {
            stat = conexao.prepareStatement(SQL);
            stat.setString(1, txt_Username.getText());
            stat.setString(2, txtp_senha.getText());
            rst = stat.executeQuery();

            if (rst.next()) {

                funcionario.setId_registroFuncionario(rst.getString(1));
                funcionario.setCodigo(rst.getString(2));
                funcionario.setApelido(rst.getString(3));
                funcionario.setNome(rst.getString(4));
                funcionario.setGenero(rst.getString(5));
                funcionario.setDatadeNascimento(rst.getString(6));
                funcionario.setNumeroDeBI(rst.getString(7));
                funcionario.setNuit(rst.getString(8));
                funcionario.setContacto(rst.getString(9));
                funcionario.setEmail(rst.getString(10));
                funcionario.setSenha(rst.getString(11));
                // nivel de acesso

                categoria.setCategoria(rst.getString(17));
                funcionario.setNivelDeAcesso(categoria);
                // provincia

                provincia.setProvicias(rst.getString(20));
                funcionario.setProvincia(provincia);

                TelaMenu tMenu = new TelaMenu();

                //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                if (rst.getString(12).equalsIgnoreCase("Activo")) {

                    if (rst.getString(17).equalsIgnoreCase("Director Geral")) {
                        tMenu.TelaMenu(funcionario);
                        tMenu.setVisible(true);
                        this.dispose();
                    } else if (rst.getString(17).equalsIgnoreCase("Gestor")) {
                        tMenu.TelaMenu(funcionario);
                        tMenu.setVisible(true);
                        tMenu.jMenu2.setVisible(false);
                        tMenu.jMenu3.setVisible(false);

                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(null, "Acesso de Funcionário nao definido!", "", JOptionPane.INFORMATION_MESSAGE);
                    }

                } else if (rst.getString(12).equalsIgnoreCase("Inativo")) {
                    JOptionPane.showInternalMessageDialog(null, "Usuário bloqueado acesso não permetido!", "Notificação", JOptionPane.INFORMATION_MESSAGE);
                    limparCampos();
                } else if (rst.getString(12).equalsIgnoreCase("removido")) {
                    JOptionPane.showInternalMessageDialog(null, "Esse Usuario não existe!", "Notificação", JOptionPane.INFORMATION_MESSAGE);
                    limparCampos();
                } // fim status
            } else if (tentativaAtual <= maximoTentativas) {
                JOptionPane.showInternalMessageDialog(null, "Combinação de credencias incorrecta.", "Notificação", JOptionPane.INFORMATION_MESSAGE);
                limparCampos();
                maximoTentativas -= 1;
                tentativaAtual = tentativaAtual + 1;
            } else if (tentativaAtual > maximoTentativas) {
                limparCampos();
                btn_ocultar.setVisible(false);
                btn_ver.setVisible(false);
                txtp_senha.setEnabled(false);
                btn_entrar.setEnabled(false);
                txt_Username.setEnabled(false);
                lbl_recuperarSenha.setVisible(true);
                lbl_recuperarSenha.requestFocus();
                JOptionPane.showMessageDialog(null, " Tentativas Esgotadas!!\n Usuario Bloqueado", "Notificação", JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro de conexao com a base d e dados!!", "Notificação", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }

    }


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtp_senhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtp_senhaActionPerformed

    }//GEN-LAST:event_txtp_senhaActionPerformed

    private void btn_ocultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ocultarActionPerformed
        btn_ocultar.setVisible(false);
        btn_ver.setVisible(true);
        txtp_senha.setEchoChar((char) 0);

    }//GEN-LAST:event_btn_ocultarActionPerformed

    private void btn_verActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_verActionPerformed
        txtp_senha.setEchoChar('•');
        btn_ocultar.setVisible(true);
        btn_ver.setVisible(false);
    }//GEN-LAST:event_btn_verActionPerformed

    private void btn_entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_entrarActionPerformed
        camposVazios();
    }//GEN-LAST:event_btn_entrarActionPerformed

    private void btn_entrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_entrarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            camposVazios();
        }
    }//GEN-LAST:event_btn_entrarKeyPressed

    private void txt_UsernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_UsernameKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (f.validarEmail(txt_Username.getText()) == false) {
                txt_Username.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.red));
                txt_Username.requestFocus();
                lbl_iconUser.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.red));
                txtp_senha.setEnabled(false);
                btn_ver.setVisible(false);
            } else {
                txtp_senha.setEnabled(true);
                btn_ver.setVisible(true);
                txtp_senha.requestFocus();
                txt_Username.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.GREEN));
                lbl_iconUser.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.GREEN));
            }
        } else if (evt.getKeyCode() == KeyEvent.VK_BACK_SPACE) {
            txt_Username.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, new Color(204, 255, 255)));
            lbl_iconUser.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, new Color(204, 255, 255)));
            //

        }
        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            txtp_senha.requestFocus();
        }

    }//GEN-LAST:event_txt_UsernameKeyPressed

    private void txtp_senhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtp_senhaKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txtp_senha.getText().isEmpty()) {
                txtp_senha.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.red));
                txtp_senha.requestFocus();
                lbl_iconSenha.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.red));

            } else {
                btn_entrar.setEnabled(true);
                btn_entrar.requestFocus();
                txtp_senha.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.GREEN));
                lbl_iconSenha.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.GREEN));
            }
        } else if (evt.getKeyCode() == KeyEvent.VK_BACK_SPACE) {
            btn_entrar.setEnabled(false);
            lbl_iconSenha.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, new Color(204, 255, 255)));
            txtp_senha.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, new Color(204, 255, 255)));

        }
        if (evt.getKeyCode() == KeyEvent.VK_UP) {
            txt_Username.requestFocus();
        }
        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            btn_entrar.requestFocus();
        }
    }//GEN-LAST:event_txtp_senhaKeyPressed

    private void lbl_recuperarSenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_recuperarSenhaMouseClicked
        entrar();
    }//GEN-LAST:event_lbl_recuperarSenhaMouseClicked

    private void btn_entrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_entrarMouseEntered
//        camposVazios();
    }//GEN-LAST:event_btn_entrarMouseEntered

    private void lbl_recuperarSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbl_recuperarSenhaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            entrar();
        }

    }//GEN-LAST:event_lbl_recuperarSenhaKeyPressed

    private void txt_UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_UsernameActionPerformed
    /**
     * @param args the command line arguments
     */

    private String dataf;
    private SimpleDateFormat sdf;
    int tentativaAtual = 1;
    int maximoTentativas = 1;
    Provincias provincia = new Provincias();
    NivelDeAcesso categoria = new NivelDeAcesso();
    Funcionario funcionario = new Funcionario();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_entrar;
    private javax.swing.JButton btn_ocultar;
    private javax.swing.JButton btn_ver;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jlbl_Icone;
    public javax.swing.JLabel lbl_Conexao;
    public javax.swing.JLabel lbl_auteticaca;
    public javax.swing.JLabel lbl_boasVindas;
    public javax.swing.JLabel lbl_border;
    public javax.swing.JLabel lbl_horaData;
    public javax.swing.JLabel lbl_iconSenha;
    public javax.swing.JLabel lbl_iconUser;
    public javax.swing.JLabel lbl_imagem;
    public javax.swing.JLabel lbl_recuperarSenha;
    protected javax.swing.JTextField txt_Username;
    public javax.swing.JPasswordField txtp_senha;
    // End of variables declaration//GEN-END:variables
  public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(recuperarConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(recuperarConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(recuperarConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(recuperarConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    private void setIconImage() {
        URL url = this.getClass().getResource("/Jail_ts2022/icons/Senha.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(iconeTitulo);
    }
}
